# TCL File Generated by Component Editor 18.1
# Thu May 21 00:01:04 IST 2026
# DO NOT MODIFY


# 
# kalman_module "Kalman Filter" v1.0
#  2026.05.21.00:01:04
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module kalman_module
# 
set_module_property DESCRIPTION ""
set_module_property NAME kalman_module
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Kalman Filter"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL kalman_wrapper
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file kalman_wrapper.v VERILOG PATH ip_cores/kalman_wrapper.v TOP_LEVEL_FILE
add_fileset_file PID.v VERILOG PATH ip_cores/PID.v
add_fileset_file ccct.v VERILOG PATH ip_cores/ccct.v
add_fileset_file cordic.v VERILOG PATH ip_cores/cordic.v
add_fileset_file div2.v VERILOG PATH ip_cores/div2.v
add_fileset_file fixedpoint_multiplier.v VERILOG PATH ip_cores/fixedpoint_multiplier.v
add_fileset_file kalman.v VERILOG PATH ip_cores/kalman.v
add_fileset_file matrix_multiplication.v VERILOG PATH ip_cores/matrix_multiplication.v
add_fileset_file mult.v VERILOG PATH ip_cores/mult.v
add_fileset_file spwm.v VERILOG PATH ip_cores/spwm.v
add_fileset_file state_update.v VERILOG PATH ip_cores/state_update.v


# 
# parameters
# 
add_parameter N INTEGER 32
set_parameter_property N DEFAULT_VALUE 32
set_parameter_property N DISPLAY_NAME N
set_parameter_property N TYPE INTEGER
set_parameter_property N UNITS None
set_parameter_property N HDL_PARAMETER true
add_parameter Q INTEGER 18
set_parameter_property Q DEFAULT_VALUE 18
set_parameter_property Q DISPLAY_NAME Q
set_parameter_property Q TYPE INTEGER
set_parameter_property Q UNITS None
set_parameter_property Q HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 5
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0

