# TCL File Generated by Component Editor 18.1
# Sun Mar 15 03:35:51 IST 2026
# DO NOT MODIFY


# 
# avalon_key_pio "Key Avalon Interfacing" v1.0
#  2026.03.15.03:35:51
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_key_pio
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_key_pio
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Key Avalon Interfacing"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_pushbuttons_logic
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_key_interface.v VERILOG PATH ../ip_cores/avalon_key_interface.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DEBOUNCE_LIMIT STD_LOGIC_VECTOR 1000000
set_parameter_property DEBOUNCE_LIMIT DEFAULT_VALUE 1000000
set_parameter_property DEBOUNCE_LIMIT DISPLAY_NAME DEBOUNCE_LIMIT
set_parameter_property DEBOUNCE_LIMIT TYPE STD_LOGIC_VECTOR
set_parameter_property DEBOUNCE_LIMIT UNITS None
set_parameter_property DEBOUNCE_LIMIT ALLOWED_RANGES 0:4194303
set_parameter_property DEBOUNCE_LIMIT HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 0
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 1
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point key_interface
# 
add_interface key_interface conduit end
set_interface_property key_interface associatedClock clock
set_interface_property key_interface associatedReset ""
set_interface_property key_interface ENABLED true
set_interface_property key_interface EXPORT_OF ""
set_interface_property key_interface PORT_NAME_MAP ""
set_interface_property key_interface CMSIS_SVD_VARIABLES ""
set_interface_property key_interface SVD_ADDRESS_GROUP ""

add_interface_port key_interface KEY export Input 2

