// signal_analyzer_IO_Modules.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module signal_analyzer_IO_Modules (
		input  wire        clk_clk,              //           clk.clk
		output wire [7:0]  hex_interface_hex_0,  // hex_interface.hex_0
		output wire [7:0]  hex_interface_hex_1,  //              .hex_1
		output wire [7:0]  hex_interface_hex_2,  //              .hex_2
		output wire [7:0]  hex_interface_hex_3,  //              .hex_3
		output wire [7:0]  hex_interface_hex_4,  //              .hex_4
		output wire [7:0]  hex_interface_hex_5,  //              .hex_5
		input  wire [1:0]  key_interface_export, // key_interface.export
		input  wire        reset_reset,          //         reset.reset
		output wire        s0_waitrequest,       //            s0.waitrequest
		output wire [31:0] s0_readdata,          //              .readdata
		output wire        s0_readdatavalid,     //              .readdatavalid
		input  wire [0:0]  s0_burstcount,        //              .burstcount
		input  wire [31:0] s0_writedata,         //              .writedata
		input  wire [9:0]  s0_address,           //              .address
		input  wire        s0_write,             //              .write
		input  wire        s0_read,              //              .read
		input  wire [3:0]  s0_byteenable,        //              .byteenable
		input  wire        s0_debugaccess,       //              .debugaccess
		input  wire [9:0]  sw_interface_export   //  sw_interface.export
	);

	wire         peripheral_bridge_m0_waitrequest;              // mm_interconnect_0:peripheral_bridge_m0_waitrequest -> peripheral_bridge:m0_waitrequest
	wire  [31:0] peripheral_bridge_m0_readdata;                 // mm_interconnect_0:peripheral_bridge_m0_readdata -> peripheral_bridge:m0_readdata
	wire         peripheral_bridge_m0_debugaccess;              // peripheral_bridge:m0_debugaccess -> mm_interconnect_0:peripheral_bridge_m0_debugaccess
	wire   [9:0] peripheral_bridge_m0_address;                  // peripheral_bridge:m0_address -> mm_interconnect_0:peripheral_bridge_m0_address
	wire         peripheral_bridge_m0_read;                     // peripheral_bridge:m0_read -> mm_interconnect_0:peripheral_bridge_m0_read
	wire   [3:0] peripheral_bridge_m0_byteenable;               // peripheral_bridge:m0_byteenable -> mm_interconnect_0:peripheral_bridge_m0_byteenable
	wire         peripheral_bridge_m0_readdatavalid;            // mm_interconnect_0:peripheral_bridge_m0_readdatavalid -> peripheral_bridge:m0_readdatavalid
	wire  [31:0] peripheral_bridge_m0_writedata;                // peripheral_bridge:m0_writedata -> mm_interconnect_0:peripheral_bridge_m0_writedata
	wire         peripheral_bridge_m0_write;                    // peripheral_bridge:m0_write -> mm_interconnect_0:peripheral_bridge_m0_write
	wire   [0:0] peripheral_bridge_m0_burstcount;               // peripheral_bridge:m0_burstcount -> mm_interconnect_0:peripheral_bridge_m0_burstcount
	wire  [31:0] mm_interconnect_0_avalon_sw_pio_s0_readdata;   // avalon_sw_pio:avs_s0_readdata -> mm_interconnect_0:avalon_sw_pio_s0_readdata
	wire   [0:0] mm_interconnect_0_avalon_sw_pio_s0_address;    // mm_interconnect_0:avalon_sw_pio_s0_address -> avalon_sw_pio:avs_s0_address
	wire         mm_interconnect_0_avalon_sw_pio_s0_read;       // mm_interconnect_0:avalon_sw_pio_s0_read -> avalon_sw_pio:avs_s0_read
	wire  [31:0] mm_interconnect_0_avalon_key_pio_s0_readdata;  // avalon_key_pio:avs_s0_readdata -> mm_interconnect_0:avalon_key_pio_s0_readdata
	wire   [0:0] mm_interconnect_0_avalon_key_pio_s0_address;   // mm_interconnect_0:avalon_key_pio_s0_address -> avalon_key_pio:avs_s0_address
	wire         mm_interconnect_0_avalon_key_pio_s0_read;      // mm_interconnect_0:avalon_key_pio_s0_read -> avalon_key_pio:avs_s0_read
	wire  [31:0] mm_interconnect_0_avalon_hex_pio_s0_readdata;  // avalon_hex_pio:avs_s0_readdata -> mm_interconnect_0:avalon_hex_pio_s0_readdata
	wire   [0:0] mm_interconnect_0_avalon_hex_pio_s0_address;   // mm_interconnect_0:avalon_hex_pio_s0_address -> avalon_hex_pio:avs_s0_address
	wire         mm_interconnect_0_avalon_hex_pio_s0_read;      // mm_interconnect_0:avalon_hex_pio_s0_read -> avalon_hex_pio:avs_s0_read
	wire         mm_interconnect_0_avalon_hex_pio_s0_write;     // mm_interconnect_0:avalon_hex_pio_s0_write -> avalon_hex_pio:avs_s0_write
	wire  [31:0] mm_interconnect_0_avalon_hex_pio_s0_writedata; // mm_interconnect_0:avalon_hex_pio_s0_writedata -> avalon_hex_pio:avs_s0_writedata

	avalon_display_logic avalon_hex_pio (
		.clk              (clk_clk),                                       //         clock.clk
		.reset            (reset_reset),                                   //         reset.reset
		.avs_s0_address   (mm_interconnect_0_avalon_hex_pio_s0_address),   //            s0.address
		.avs_s0_write     (mm_interconnect_0_avalon_hex_pio_s0_write),     //              .write
		.avs_s0_writedata (mm_interconnect_0_avalon_hex_pio_s0_writedata), //              .writedata
		.avs_s0_read      (mm_interconnect_0_avalon_hex_pio_s0_read),      //              .read
		.avs_s0_readdata  (mm_interconnect_0_avalon_hex_pio_s0_readdata),  //              .readdata
		.HEX0             (hex_interface_hex_0),                           // hex_interface.hex_0
		.HEX1             (hex_interface_hex_1),                           //              .hex_1
		.HEX2             (hex_interface_hex_2),                           //              .hex_2
		.HEX3             (hex_interface_hex_3),                           //              .hex_3
		.HEX4             (hex_interface_hex_4),                           //              .hex_4
		.HEX5             (hex_interface_hex_5)                            //              .hex_5
	);

	avalon_pushbuttons_logic #(
		.DEBOUNCE_LIMIT (22'b0011110100001001000000)
	) avalon_key_pio (
		.clk             (clk_clk),                                      //         clock.clk
		.reset           (reset_reset),                                  //         reset.reset
		.avs_s0_address  (mm_interconnect_0_avalon_key_pio_s0_address),  //            s0.address
		.avs_s0_read     (mm_interconnect_0_avalon_key_pio_s0_read),     //              .read
		.avs_s0_readdata (mm_interconnect_0_avalon_key_pio_s0_readdata), //              .readdata
		.KEY             (key_interface_export)                          // key_interface.export
	);

	avalon_switches_logic avalon_sw_pio (
		.clk             (clk_clk),                                     //        clock.clk
		.reset           (reset_reset),                                 //        reset.reset
		.avs_s0_address  (mm_interconnect_0_avalon_sw_pio_s0_address),  //           s0.address
		.avs_s0_read     (mm_interconnect_0_avalon_sw_pio_s0_read),     //             .read
		.avs_s0_readdata (mm_interconnect_0_avalon_sw_pio_s0_readdata), //             .readdata
		.SW              (sw_interface_export)                          // sw_interface.export
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (10),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) peripheral_bridge (
		.clk              (clk_clk),                            //   clk.clk
		.reset            (reset_reset),                        // reset.reset
		.s0_waitrequest   (s0_waitrequest),                     //    s0.waitrequest
		.s0_readdata      (s0_readdata),                        //      .readdata
		.s0_readdatavalid (s0_readdatavalid),                   //      .readdatavalid
		.s0_burstcount    (s0_burstcount),                      //      .burstcount
		.s0_writedata     (s0_writedata),                       //      .writedata
		.s0_address       (s0_address),                         //      .address
		.s0_write         (s0_write),                           //      .write
		.s0_read          (s0_read),                            //      .read
		.s0_byteenable    (s0_byteenable),                      //      .byteenable
		.s0_debugaccess   (s0_debugaccess),                     //      .debugaccess
		.m0_waitrequest   (peripheral_bridge_m0_waitrequest),   //    m0.waitrequest
		.m0_readdata      (peripheral_bridge_m0_readdata),      //      .readdata
		.m0_readdatavalid (peripheral_bridge_m0_readdatavalid), //      .readdatavalid
		.m0_burstcount    (peripheral_bridge_m0_burstcount),    //      .burstcount
		.m0_writedata     (peripheral_bridge_m0_writedata),     //      .writedata
		.m0_address       (peripheral_bridge_m0_address),       //      .address
		.m0_write         (peripheral_bridge_m0_write),         //      .write
		.m0_read          (peripheral_bridge_m0_read),          //      .read
		.m0_byteenable    (peripheral_bridge_m0_byteenable),    //      .byteenable
		.m0_debugaccess   (peripheral_bridge_m0_debugaccess),   //      .debugaccess
		.s0_response      (),                                   // (terminated)
		.m0_response      (2'b00)                               // (terminated)
	);

	signal_analyzer_IO_Modules_mm_interconnect_0 mm_interconnect_0 (
		.clock_out_clk_clk                                   (clk_clk),                                       //                                 clock_out_clk.clk
		.peripheral_bridge_reset_reset_bridge_in_reset_reset (reset_reset),                                   // peripheral_bridge_reset_reset_bridge_in_reset.reset
		.peripheral_bridge_m0_address                        (peripheral_bridge_m0_address),                  //                          peripheral_bridge_m0.address
		.peripheral_bridge_m0_waitrequest                    (peripheral_bridge_m0_waitrequest),              //                                              .waitrequest
		.peripheral_bridge_m0_burstcount                     (peripheral_bridge_m0_burstcount),               //                                              .burstcount
		.peripheral_bridge_m0_byteenable                     (peripheral_bridge_m0_byteenable),               //                                              .byteenable
		.peripheral_bridge_m0_read                           (peripheral_bridge_m0_read),                     //                                              .read
		.peripheral_bridge_m0_readdata                       (peripheral_bridge_m0_readdata),                 //                                              .readdata
		.peripheral_bridge_m0_readdatavalid                  (peripheral_bridge_m0_readdatavalid),            //                                              .readdatavalid
		.peripheral_bridge_m0_write                          (peripheral_bridge_m0_write),                    //                                              .write
		.peripheral_bridge_m0_writedata                      (peripheral_bridge_m0_writedata),                //                                              .writedata
		.peripheral_bridge_m0_debugaccess                    (peripheral_bridge_m0_debugaccess),              //                                              .debugaccess
		.avalon_hex_pio_s0_address                           (mm_interconnect_0_avalon_hex_pio_s0_address),   //                             avalon_hex_pio_s0.address
		.avalon_hex_pio_s0_write                             (mm_interconnect_0_avalon_hex_pio_s0_write),     //                                              .write
		.avalon_hex_pio_s0_read                              (mm_interconnect_0_avalon_hex_pio_s0_read),      //                                              .read
		.avalon_hex_pio_s0_readdata                          (mm_interconnect_0_avalon_hex_pio_s0_readdata),  //                                              .readdata
		.avalon_hex_pio_s0_writedata                         (mm_interconnect_0_avalon_hex_pio_s0_writedata), //                                              .writedata
		.avalon_key_pio_s0_address                           (mm_interconnect_0_avalon_key_pio_s0_address),   //                             avalon_key_pio_s0.address
		.avalon_key_pio_s0_read                              (mm_interconnect_0_avalon_key_pio_s0_read),      //                                              .read
		.avalon_key_pio_s0_readdata                          (mm_interconnect_0_avalon_key_pio_s0_readdata),  //                                              .readdata
		.avalon_sw_pio_s0_address                            (mm_interconnect_0_avalon_sw_pio_s0_address),    //                              avalon_sw_pio_s0.address
		.avalon_sw_pio_s0_read                               (mm_interconnect_0_avalon_sw_pio_s0_read),       //                                              .read
		.avalon_sw_pio_s0_readdata                           (mm_interconnect_0_avalon_sw_pio_s0_readdata)    //                                              .readdata
	);

endmodule
