// signal_analyzer_GPIO.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module signal_analyzer_GPIO (
		input  wire        clk_clk,               //            clk.clk
		output wire        csr_irq_irq,           //        csr_irq.irq
		inout  wire [35:0] gpio_interface_export, // gpio_interface.export
		output wire [25:0] mm_write_address,      //       mm_write.address
		output wire        mm_write_write,        //               .write
		output wire [7:0]  mm_write_byteenable,   //               .byteenable
		output wire [63:0] mm_write_writedata,    //               .writedata
		input  wire        mm_write_waitrequest,  //               .waitrequest
		input  wire        reset_reset,           //          reset.reset
		output wire        s0_waitrequest,        //             s0.waitrequest
		output wire [31:0] s0_readdata,           //               .readdata
		output wire        s0_readdatavalid,      //               .readdatavalid
		input  wire [0:0]  s0_burstcount,         //               .burstcount
		input  wire [31:0] s0_writedata,          //               .writedata
		input  wire [9:0]  s0_address,            //               .address
		input  wire        s0_write,              //               .write
		input  wire        s0_read,               //               .read
		input  wire [3:0]  s0_byteenable,         //               .byteenable
		input  wire        s0_debugaccess         //               .debugaccess
	);

	wire          avalon_gpio_interface_0_avalon_streaming_source_valid;  // avalon_gpio_interface_0:aso_valid -> DMA:st_sink_valid
	wire   [63:0] avalon_gpio_interface_0_avalon_streaming_source_data;   // avalon_gpio_interface_0:aso_data -> DMA:st_sink_data
	wire          avalon_gpio_interface_0_avalon_streaming_source_ready;  // DMA:st_sink_ready -> avalon_gpio_interface_0:aso_ready
	wire          peripheral_bridge_m0_waitrequest;                       // mm_interconnect_0:peripheral_bridge_m0_waitrequest -> peripheral_bridge:m0_waitrequest
	wire   [31:0] peripheral_bridge_m0_readdata;                          // mm_interconnect_0:peripheral_bridge_m0_readdata -> peripheral_bridge:m0_readdata
	wire          peripheral_bridge_m0_debugaccess;                       // peripheral_bridge:m0_debugaccess -> mm_interconnect_0:peripheral_bridge_m0_debugaccess
	wire    [9:0] peripheral_bridge_m0_address;                           // peripheral_bridge:m0_address -> mm_interconnect_0:peripheral_bridge_m0_address
	wire          peripheral_bridge_m0_read;                              // peripheral_bridge:m0_read -> mm_interconnect_0:peripheral_bridge_m0_read
	wire    [3:0] peripheral_bridge_m0_byteenable;                        // peripheral_bridge:m0_byteenable -> mm_interconnect_0:peripheral_bridge_m0_byteenable
	wire          peripheral_bridge_m0_readdatavalid;                     // mm_interconnect_0:peripheral_bridge_m0_readdatavalid -> peripheral_bridge:m0_readdatavalid
	wire   [31:0] peripheral_bridge_m0_writedata;                         // peripheral_bridge:m0_writedata -> mm_interconnect_0:peripheral_bridge_m0_writedata
	wire          peripheral_bridge_m0_write;                             // peripheral_bridge:m0_write -> mm_interconnect_0:peripheral_bridge_m0_write
	wire    [0:0] peripheral_bridge_m0_burstcount;                        // peripheral_bridge:m0_burstcount -> mm_interconnect_0:peripheral_bridge_m0_burstcount
	wire   [31:0] mm_interconnect_0_dma_csr_readdata;                     // DMA:csr_readdata -> mm_interconnect_0:DMA_csr_readdata
	wire    [2:0] mm_interconnect_0_dma_csr_address;                      // mm_interconnect_0:DMA_csr_address -> DMA:csr_address
	wire          mm_interconnect_0_dma_csr_read;                         // mm_interconnect_0:DMA_csr_read -> DMA:csr_read
	wire    [3:0] mm_interconnect_0_dma_csr_byteenable;                   // mm_interconnect_0:DMA_csr_byteenable -> DMA:csr_byteenable
	wire          mm_interconnect_0_dma_csr_write;                        // mm_interconnect_0:DMA_csr_write -> DMA:csr_write
	wire   [31:0] mm_interconnect_0_dma_csr_writedata;                    // mm_interconnect_0:DMA_csr_writedata -> DMA:csr_writedata
	wire          mm_interconnect_0_dma_descriptor_slave_waitrequest;     // DMA:descriptor_slave_waitrequest -> mm_interconnect_0:DMA_descriptor_slave_waitrequest
	wire   [15:0] mm_interconnect_0_dma_descriptor_slave_byteenable;      // mm_interconnect_0:DMA_descriptor_slave_byteenable -> DMA:descriptor_slave_byteenable
	wire          mm_interconnect_0_dma_descriptor_slave_write;           // mm_interconnect_0:DMA_descriptor_slave_write -> DMA:descriptor_slave_write
	wire  [127:0] mm_interconnect_0_dma_descriptor_slave_writedata;       // mm_interconnect_0:DMA_descriptor_slave_writedata -> DMA:descriptor_slave_writedata
	wire   [31:0] mm_interconnect_0_avalon_gpio_interface_0_s0_readdata;  // avalon_gpio_interface_0:avs_s0_readdata -> mm_interconnect_0:avalon_gpio_interface_0_s0_readdata
	wire    [1:0] mm_interconnect_0_avalon_gpio_interface_0_s0_address;   // mm_interconnect_0:avalon_gpio_interface_0_s0_address -> avalon_gpio_interface_0:avs_s0_address
	wire          mm_interconnect_0_avalon_gpio_interface_0_s0_read;      // mm_interconnect_0:avalon_gpio_interface_0_s0_read -> avalon_gpio_interface_0:avs_s0_read
	wire          mm_interconnect_0_avalon_gpio_interface_0_s0_write;     // mm_interconnect_0:avalon_gpio_interface_0_s0_write -> avalon_gpio_interface_0:avs_s0_write
	wire   [31:0] mm_interconnect_0_avalon_gpio_interface_0_s0_writedata; // mm_interconnect_0:avalon_gpio_interface_0_s0_writedata -> avalon_gpio_interface_0:avs_s0_writedata

	signal_analyzer_GPIO_DMA dma (
		.mm_write_address             (mm_write_address),                                      //         mm_write.address
		.mm_write_write               (mm_write_write),                                        //                 .write
		.mm_write_byteenable          (mm_write_byteenable),                                   //                 .byteenable
		.mm_write_writedata           (mm_write_writedata),                                    //                 .writedata
		.mm_write_waitrequest         (mm_write_waitrequest),                                  //                 .waitrequest
		.clock_clk                    (clk_clk),                                               //            clock.clk
		.reset_n_reset_n              (~reset_reset),                                          //          reset_n.reset_n
		.csr_writedata                (mm_interconnect_0_dma_csr_writedata),                   //              csr.writedata
		.csr_write                    (mm_interconnect_0_dma_csr_write),                       //                 .write
		.csr_byteenable               (mm_interconnect_0_dma_csr_byteenable),                  //                 .byteenable
		.csr_readdata                 (mm_interconnect_0_dma_csr_readdata),                    //                 .readdata
		.csr_read                     (mm_interconnect_0_dma_csr_read),                        //                 .read
		.csr_address                  (mm_interconnect_0_dma_csr_address),                     //                 .address
		.descriptor_slave_write       (mm_interconnect_0_dma_descriptor_slave_write),          // descriptor_slave.write
		.descriptor_slave_waitrequest (mm_interconnect_0_dma_descriptor_slave_waitrequest),    //                 .waitrequest
		.descriptor_slave_writedata   (mm_interconnect_0_dma_descriptor_slave_writedata),      //                 .writedata
		.descriptor_slave_byteenable  (mm_interconnect_0_dma_descriptor_slave_byteenable),     //                 .byteenable
		.csr_irq_irq                  (csr_irq_irq),                                           //          csr_irq.irq
		.st_sink_data                 (avalon_gpio_interface_0_avalon_streaming_source_data),  //          st_sink.data
		.st_sink_valid                (avalon_gpio_interface_0_avalon_streaming_source_valid), //                 .valid
		.st_sink_ready                (avalon_gpio_interface_0_avalon_streaming_source_ready)  //                 .ready
	);

	avalon_gpio_interface avalon_gpio_interface_0 (
		.clk              (clk_clk),                                                //                   clock.clk
		.reset            (reset_reset),                                            //                   reset.reset
		.avs_s0_address   (mm_interconnect_0_avalon_gpio_interface_0_s0_address),   //                      s0.address
		.avs_s0_write     (mm_interconnect_0_avalon_gpio_interface_0_s0_write),     //                        .write
		.avs_s0_writedata (mm_interconnect_0_avalon_gpio_interface_0_s0_writedata), //                        .writedata
		.avs_s0_read      (mm_interconnect_0_avalon_gpio_interface_0_s0_read),      //                        .read
		.avs_s0_readdata  (mm_interconnect_0_avalon_gpio_interface_0_s0_readdata),  //                        .readdata
		.GPIO             (gpio_interface_export),                                  //          gpio_interface.export
		.aso_data         (avalon_gpio_interface_0_avalon_streaming_source_data),   // avalon_streaming_source.data
		.aso_valid        (avalon_gpio_interface_0_avalon_streaming_source_valid),  //                        .valid
		.aso_ready        (avalon_gpio_interface_0_avalon_streaming_source_ready)   //                        .ready
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (10),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) peripheral_bridge (
		.clk              (clk_clk),                            //   clk.clk
		.reset            (reset_reset),                        // reset.reset
		.s0_waitrequest   (s0_waitrequest),                     //    s0.waitrequest
		.s0_readdata      (s0_readdata),                        //      .readdata
		.s0_readdatavalid (s0_readdatavalid),                   //      .readdatavalid
		.s0_burstcount    (s0_burstcount),                      //      .burstcount
		.s0_writedata     (s0_writedata),                       //      .writedata
		.s0_address       (s0_address),                         //      .address
		.s0_write         (s0_write),                           //      .write
		.s0_read          (s0_read),                            //      .read
		.s0_byteenable    (s0_byteenable),                      //      .byteenable
		.s0_debugaccess   (s0_debugaccess),                     //      .debugaccess
		.m0_waitrequest   (peripheral_bridge_m0_waitrequest),   //    m0.waitrequest
		.m0_readdata      (peripheral_bridge_m0_readdata),      //      .readdata
		.m0_readdatavalid (peripheral_bridge_m0_readdatavalid), //      .readdatavalid
		.m0_burstcount    (peripheral_bridge_m0_burstcount),    //      .burstcount
		.m0_writedata     (peripheral_bridge_m0_writedata),     //      .writedata
		.m0_address       (peripheral_bridge_m0_address),       //      .address
		.m0_write         (peripheral_bridge_m0_write),         //      .write
		.m0_read          (peripheral_bridge_m0_read),          //      .read
		.m0_byteenable    (peripheral_bridge_m0_byteenable),    //      .byteenable
		.m0_debugaccess   (peripheral_bridge_m0_debugaccess),   //      .debugaccess
		.s0_response      (),                                   // (terminated)
		.m0_response      (2'b00)                               // (terminated)
	);

	signal_analyzer_GPIO_mm_interconnect_0 mm_interconnect_0 (
		.clock_bridge_0_out_clk_clk                          (clk_clk),                                                //                        clock_bridge_0_out_clk.clk
		.peripheral_bridge_reset_reset_bridge_in_reset_reset (reset_reset),                                            // peripheral_bridge_reset_reset_bridge_in_reset.reset
		.peripheral_bridge_m0_address                        (peripheral_bridge_m0_address),                           //                          peripheral_bridge_m0.address
		.peripheral_bridge_m0_waitrequest                    (peripheral_bridge_m0_waitrequest),                       //                                              .waitrequest
		.peripheral_bridge_m0_burstcount                     (peripheral_bridge_m0_burstcount),                        //                                              .burstcount
		.peripheral_bridge_m0_byteenable                     (peripheral_bridge_m0_byteenable),                        //                                              .byteenable
		.peripheral_bridge_m0_read                           (peripheral_bridge_m0_read),                              //                                              .read
		.peripheral_bridge_m0_readdata                       (peripheral_bridge_m0_readdata),                          //                                              .readdata
		.peripheral_bridge_m0_readdatavalid                  (peripheral_bridge_m0_readdatavalid),                     //                                              .readdatavalid
		.peripheral_bridge_m0_write                          (peripheral_bridge_m0_write),                             //                                              .write
		.peripheral_bridge_m0_writedata                      (peripheral_bridge_m0_writedata),                         //                                              .writedata
		.peripheral_bridge_m0_debugaccess                    (peripheral_bridge_m0_debugaccess),                       //                                              .debugaccess
		.avalon_gpio_interface_0_s0_address                  (mm_interconnect_0_avalon_gpio_interface_0_s0_address),   //                    avalon_gpio_interface_0_s0.address
		.avalon_gpio_interface_0_s0_write                    (mm_interconnect_0_avalon_gpio_interface_0_s0_write),     //                                              .write
		.avalon_gpio_interface_0_s0_read                     (mm_interconnect_0_avalon_gpio_interface_0_s0_read),      //                                              .read
		.avalon_gpio_interface_0_s0_readdata                 (mm_interconnect_0_avalon_gpio_interface_0_s0_readdata),  //                                              .readdata
		.avalon_gpio_interface_0_s0_writedata                (mm_interconnect_0_avalon_gpio_interface_0_s0_writedata), //                                              .writedata
		.DMA_csr_address                                     (mm_interconnect_0_dma_csr_address),                      //                                       DMA_csr.address
		.DMA_csr_write                                       (mm_interconnect_0_dma_csr_write),                        //                                              .write
		.DMA_csr_read                                        (mm_interconnect_0_dma_csr_read),                         //                                              .read
		.DMA_csr_readdata                                    (mm_interconnect_0_dma_csr_readdata),                     //                                              .readdata
		.DMA_csr_writedata                                   (mm_interconnect_0_dma_csr_writedata),                    //                                              .writedata
		.DMA_csr_byteenable                                  (mm_interconnect_0_dma_csr_byteenable),                   //                                              .byteenable
		.DMA_descriptor_slave_write                          (mm_interconnect_0_dma_descriptor_slave_write),           //                          DMA_descriptor_slave.write
		.DMA_descriptor_slave_writedata                      (mm_interconnect_0_dma_descriptor_slave_writedata),       //                                              .writedata
		.DMA_descriptor_slave_byteenable                     (mm_interconnect_0_dma_descriptor_slave_byteenable),      //                                              .byteenable
		.DMA_descriptor_slave_waitrequest                    (mm_interconnect_0_dma_descriptor_slave_waitrequest)      //                                              .waitrequest
	);

endmodule
