# TCL File Generated by Component Editor 18.1
# Wed Mar 04 17:36:06 IST 2026
# DO NOT MODIFY


# 
# full_adder_4bit "4-Bit Full Adder" v1.0
#  2026.03.04.17:36:06
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module full_adder_4bit
# 
set_module_property DESCRIPTION ""
set_module_property NAME full_adder_4bit
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "4-Bit Full Adder"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL full_adder_4bit
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file full_adder_4bit.v VERILOG PATH ../ip_cores/full_adder_4bit.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point fa_signals
# 
add_interface fa_signals conduit end
set_interface_property fa_signals associatedClock ""
set_interface_property fa_signals associatedReset ""
set_interface_property fa_signals ENABLED true
set_interface_property fa_signals EXPORT_OF ""
set_interface_property fa_signals PORT_NAME_MAP ""
set_interface_property fa_signals CMSIS_SVD_VARIABLES ""
set_interface_property fa_signals SVD_ADDRESS_GROUP ""

add_interface_port fa_signals a fa_a Input 4
add_interface_port fa_signals b fa_b Input 4
add_interface_port fa_signals sum fa_sum Output 4
add_interface_port fa_signals carry fa_carry Output 1

