# TCL File Generated by Component Editor 18.1
# Wed Mar 04 17:37:35 IST 2026
# DO NOT MODIFY


# 
# hex_display "7 Segment Display" v1.0
#  2026.03.04.17:37:35
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module hex_display
# 
set_module_property DESCRIPTION ""
set_module_property NAME hex_display
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "7 Segment Display"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL HexDigit_Decoder
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file hex_disp.v VERILOG PATH ../ip_cores/hex_disp.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point hex_display
# 
add_interface hex_display conduit end
set_interface_property hex_display associatedClock ""
set_interface_property hex_display associatedReset ""
set_interface_property hex_display ENABLED true
set_interface_property hex_display EXPORT_OF ""
set_interface_property hex_display PORT_NAME_MAP ""
set_interface_property hex_display CMSIS_SVD_VARIABLES ""
set_interface_property hex_display SVD_ADDRESS_GROUP ""

add_interface_port hex_display hex_input input Input 4
add_interface_port hex_display seg_output output Output 8

