# TCL File Generated by Component Editor 18.1
# Wed Mar 04 17:39:03 IST 2026
# DO NOT MODIFY


# 
# key_register "Register Key Deboucer" v1.0
#  2026.03.04.17:39:03
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module key_register
# 
set_module_property DESCRIPTION ""
set_module_property NAME key_register
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Register Key Deboucer"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL key_debounce
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file key_register.v VERILOG PATH ../ip_cores/key_register.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point key_debouncer
# 
add_interface key_debouncer conduit end
set_interface_property key_debouncer associatedClock clock
set_interface_property key_debouncer associatedReset ""
set_interface_property key_debouncer ENABLED true
set_interface_property key_debouncer EXPORT_OF ""
set_interface_property key_debouncer PORT_NAME_MAP ""
set_interface_property key_debouncer CMSIS_SVD_VARIABLES ""
set_interface_property key_debouncer SVD_ADDRESS_GROUP ""

add_interface_port key_debouncer key_n input Input 1
add_interface_port key_debouncer key_pulse output Output 1

