// avalon_design.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module avalon_design (
		input  wire [1:0] button_interface_export, // button_interface.export
		input  wire       clk_clk,                 //              clk.clk
		output wire [7:0] hex_interface_hex_0,     //    hex_interface.hex_0
		output wire [7:0] hex_interface_hex_1,     //                 .hex_1
		output wire [7:0] hex_interface_hex_2,     //                 .hex_2
		output wire [7:0] hex_interface_hex_3,     //                 .hex_3
		output wire [7:0] hex_interface_hex_4,     //                 .hex_4
		output wire [7:0] hex_interface_hex_5,     //                 .hex_5
		output wire       led_interface_export     //    led_interface.export
	);

	wire         nios_ii_debug_reset_request_reset;                                       // NIOS_II:debug_reset_request -> [rst_controller:reset_in0, rst_controller:reset_in1, rst_controller_001:reset_in0]
	wire  [31:0] nios_ii_data_master_readdata;                                            // mm_interconnect_0:NIOS_II_data_master_readdata -> NIOS_II:d_readdata
	wire         nios_ii_data_master_waitrequest;                                         // mm_interconnect_0:NIOS_II_data_master_waitrequest -> NIOS_II:d_waitrequest
	wire         nios_ii_data_master_debugaccess;                                         // NIOS_II:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOS_II_data_master_debugaccess
	wire  [18:0] nios_ii_data_master_address;                                             // NIOS_II:d_address -> mm_interconnect_0:NIOS_II_data_master_address
	wire   [3:0] nios_ii_data_master_byteenable;                                          // NIOS_II:d_byteenable -> mm_interconnect_0:NIOS_II_data_master_byteenable
	wire         nios_ii_data_master_read;                                                // NIOS_II:d_read -> mm_interconnect_0:NIOS_II_data_master_read
	wire         nios_ii_data_master_readdatavalid;                                       // mm_interconnect_0:NIOS_II_data_master_readdatavalid -> NIOS_II:d_readdatavalid
	wire         nios_ii_data_master_write;                                               // NIOS_II:d_write -> mm_interconnect_0:NIOS_II_data_master_write
	wire  [31:0] nios_ii_data_master_writedata;                                           // NIOS_II:d_writedata -> mm_interconnect_0:NIOS_II_data_master_writedata
	wire  [31:0] nios_ii_instruction_master_readdata;                                     // mm_interconnect_0:NIOS_II_instruction_master_readdata -> NIOS_II:i_readdata
	wire         nios_ii_instruction_master_waitrequest;                                  // mm_interconnect_0:NIOS_II_instruction_master_waitrequest -> NIOS_II:i_waitrequest
	wire  [18:0] nios_ii_instruction_master_address;                                      // NIOS_II:i_address -> mm_interconnect_0:NIOS_II_instruction_master_address
	wire         nios_ii_instruction_master_read;                                         // NIOS_II:i_read -> mm_interconnect_0:NIOS_II_instruction_master_read
	wire         nios_ii_instruction_master_readdatavalid;                                // mm_interconnect_0:NIOS_II_instruction_master_readdatavalid -> NIOS_II:i_readdatavalid
	wire         mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_chipselect;  // mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_chipselect -> mem_sys_subsystem:DEBUG_avalon_jtag_slave_chipselect
	wire  [31:0] mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_readdata;    // mem_sys_subsystem:DEBUG_avalon_jtag_slave_readdata -> mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_waitrequest; // mem_sys_subsystem:DEBUG_avalon_jtag_slave_waitrequest -> mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_address;     // mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_address -> mem_sys_subsystem:DEBUG_avalon_jtag_slave_address
	wire         mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_read;        // mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_read -> mem_sys_subsystem:DEBUG_avalon_jtag_slave_read_n
	wire         mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_write;       // mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_write -> mem_sys_subsystem:DEBUG_avalon_jtag_slave_write_n
	wire  [31:0] mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_writedata;   // mm_interconnect_0:mem_sys_subsystem_DEBUG_avalon_jtag_slave_writedata -> mem_sys_subsystem:DEBUG_avalon_jtag_slave_writedata
	wire         mm_interconnect_0_mem_sys_subsystem_sram_s1_chipselect;                  // mm_interconnect_0:mem_sys_subsystem_SRAM_s1_chipselect -> mem_sys_subsystem:SRAM_s1_chipselect
	wire  [31:0] mm_interconnect_0_mem_sys_subsystem_sram_s1_readdata;                    // mem_sys_subsystem:SRAM_s1_readdata -> mm_interconnect_0:mem_sys_subsystem_SRAM_s1_readdata
	wire  [14:0] mm_interconnect_0_mem_sys_subsystem_sram_s1_address;                     // mm_interconnect_0:mem_sys_subsystem_SRAM_s1_address -> mem_sys_subsystem:SRAM_s1_address
	wire   [3:0] mm_interconnect_0_mem_sys_subsystem_sram_s1_byteenable;                  // mm_interconnect_0:mem_sys_subsystem_SRAM_s1_byteenable -> mem_sys_subsystem:SRAM_s1_byteenable
	wire         mm_interconnect_0_mem_sys_subsystem_sram_s1_write;                       // mm_interconnect_0:mem_sys_subsystem_SRAM_s1_write -> mem_sys_subsystem:SRAM_s1_write
	wire  [31:0] mm_interconnect_0_mem_sys_subsystem_sram_s1_writedata;                   // mm_interconnect_0:mem_sys_subsystem_SRAM_s1_writedata -> mem_sys_subsystem:SRAM_s1_writedata
	wire         mm_interconnect_0_mem_sys_subsystem_sram_s1_clken;                       // mm_interconnect_0:mem_sys_subsystem_SRAM_s1_clken -> mem_sys_subsystem:SRAM_s1_clken
	wire  [31:0] mm_interconnect_0_mem_sys_subsystem_sys_id_control_slave_readdata;       // mem_sys_subsystem:SYS_ID_control_slave_readdata -> mm_interconnect_0:mem_sys_subsystem_SYS_ID_control_slave_readdata
	wire   [0:0] mm_interconnect_0_mem_sys_subsystem_sys_id_control_slave_address;        // mm_interconnect_0:mem_sys_subsystem_SYS_ID_control_slave_address -> mem_sys_subsystem:SYS_ID_control_slave_address
	wire  [31:0] mm_interconnect_0_nios_ii_debug_mem_slave_readdata;                      // NIOS_II:debug_mem_slave_readdata -> mm_interconnect_0:NIOS_II_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest;                   // NIOS_II:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOS_II_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess;                   // mm_interconnect_0:NIOS_II_debug_mem_slave_debugaccess -> NIOS_II:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios_ii_debug_mem_slave_address;                       // mm_interconnect_0:NIOS_II_debug_mem_slave_address -> NIOS_II:debug_mem_slave_address
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_read;                          // mm_interconnect_0:NIOS_II_debug_mem_slave_read -> NIOS_II:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios_ii_debug_mem_slave_byteenable;                    // mm_interconnect_0:NIOS_II_debug_mem_slave_byteenable -> NIOS_II:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_write;                         // mm_interconnect_0:NIOS_II_debug_mem_slave_write -> NIOS_II:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios_ii_debug_mem_slave_writedata;                     // mm_interconnect_0:NIOS_II_debug_mem_slave_writedata -> NIOS_II:debug_mem_slave_writedata
	wire  [31:0] mm_interconnect_0_io_peripherals_s0_readdata;                            // io_peripherals:s0_readdata -> mm_interconnect_0:io_peripherals_s0_readdata
	wire         mm_interconnect_0_io_peripherals_s0_waitrequest;                         // io_peripherals:s0_waitrequest -> mm_interconnect_0:io_peripherals_s0_waitrequest
	wire         mm_interconnect_0_io_peripherals_s0_debugaccess;                         // mm_interconnect_0:io_peripherals_s0_debugaccess -> io_peripherals:s0_debugaccess
	wire   [9:0] mm_interconnect_0_io_peripherals_s0_address;                             // mm_interconnect_0:io_peripherals_s0_address -> io_peripherals:s0_address
	wire         mm_interconnect_0_io_peripherals_s0_read;                                // mm_interconnect_0:io_peripherals_s0_read -> io_peripherals:s0_read
	wire   [3:0] mm_interconnect_0_io_peripherals_s0_byteenable;                          // mm_interconnect_0:io_peripherals_s0_byteenable -> io_peripherals:s0_byteenable
	wire         mm_interconnect_0_io_peripherals_s0_readdatavalid;                       // io_peripherals:s0_readdatavalid -> mm_interconnect_0:io_peripherals_s0_readdatavalid
	wire         mm_interconnect_0_io_peripherals_s0_write;                               // mm_interconnect_0:io_peripherals_s0_write -> io_peripherals:s0_write
	wire  [31:0] mm_interconnect_0_io_peripherals_s0_writedata;                           // mm_interconnect_0:io_peripherals_s0_writedata -> io_peripherals:s0_writedata
	wire   [0:0] mm_interconnect_0_io_peripherals_s0_burstcount;                          // mm_interconnect_0:io_peripherals_s0_burstcount -> io_peripherals:s0_burstcount
	wire         irq_mapper_receiver0_irq;                                                // mem_sys_subsystem:DEBUG_irq_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios_ii_irq_irq;                                                         // irq_mapper:sender_irq -> NIOS_II:irq
	wire         rst_controller_reset_out_reset;                                          // rst_controller:reset_out -> [NIOS_II:reset_n, irq_mapper:reset, mm_interconnect_0:NIOS_II_reset_reset_bridge_in_reset_reset]
	wire         rst_controller_reset_out_reset_req;                                      // rst_controller:reset_req -> [NIOS_II:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                                      // rst_controller_001:reset_out -> [io_peripherals:reset_reset, mem_sys_subsystem:reset_reset, mm_interconnect_0:mem_sys_subsystem_reset_reset_bridge_in_reset_reset]

	avalon_design_NIOS_II nios_ii (
		.clk                                 (clk_clk),                                               //                       clk.clk
		.reset_n                             (~rst_controller_reset_out_reset),                       //                     reset.reset_n
		.reset_req                           (rst_controller_reset_out_reset_req),                    //                          .reset_req
		.d_address                           (nios_ii_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios_ii_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios_ii_data_master_read),                              //                          .read
		.d_readdata                          (nios_ii_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios_ii_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios_ii_data_master_write),                             //                          .write
		.d_writedata                         (nios_ii_data_master_writedata),                         //                          .writedata
		.d_readdatavalid                     (nios_ii_data_master_readdatavalid),                     //                          .readdatavalid
		.debug_mem_slave_debugaccess_to_roms (nios_ii_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios_ii_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios_ii_instruction_master_read),                       //                          .read
		.i_readdata                          (nios_ii_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios_ii_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (nios_ii_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (nios_ii_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios_ii_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios_ii_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios_ii_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios_ii_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios_ii_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios_ii_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios_ii_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                       // custom_instruction_master.readra
	);

	avalon_design_io_peripherals io_peripherals (
		.button_interface_export (button_interface_export),                           // button_interface.export
		.clk_clk                 (clk_clk),                                           //              clk.clk
		.hex_interface_hex_0     (hex_interface_hex_0),                               //    hex_interface.hex_0
		.hex_interface_hex_1     (hex_interface_hex_1),                               //                 .hex_1
		.hex_interface_hex_2     (hex_interface_hex_2),                               //                 .hex_2
		.hex_interface_hex_3     (hex_interface_hex_3),                               //                 .hex_3
		.hex_interface_hex_4     (hex_interface_hex_4),                               //                 .hex_4
		.hex_interface_hex_5     (hex_interface_hex_5),                               //                 .hex_5
		.led_interface_export    (led_interface_export),                              //    led_interface.export
		.reset_reset             (rst_controller_001_reset_out_reset),                //            reset.reset
		.s0_waitrequest          (mm_interconnect_0_io_peripherals_s0_waitrequest),   //               s0.waitrequest
		.s0_readdata             (mm_interconnect_0_io_peripherals_s0_readdata),      //                 .readdata
		.s0_readdatavalid        (mm_interconnect_0_io_peripherals_s0_readdatavalid), //                 .readdatavalid
		.s0_burstcount           (mm_interconnect_0_io_peripherals_s0_burstcount),    //                 .burstcount
		.s0_writedata            (mm_interconnect_0_io_peripherals_s0_writedata),     //                 .writedata
		.s0_address              (mm_interconnect_0_io_peripherals_s0_address),       //                 .address
		.s0_write                (mm_interconnect_0_io_peripherals_s0_write),         //                 .write
		.s0_read                 (mm_interconnect_0_io_peripherals_s0_read),          //                 .read
		.s0_byteenable           (mm_interconnect_0_io_peripherals_s0_byteenable),    //                 .byteenable
		.s0_debugaccess          (mm_interconnect_0_io_peripherals_s0_debugaccess)    //                 .debugaccess
	);

	avalon_design_mem_sys_subsystem mem_sys_subsystem (
		.DEBUG_avalon_jtag_slave_chipselect  (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_chipselect),  // DEBUG_avalon_jtag_slave.chipselect
		.DEBUG_avalon_jtag_slave_address     (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_address),     //                        .address
		.DEBUG_avalon_jtag_slave_read_n      (~mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_read),       //                        .read_n
		.DEBUG_avalon_jtag_slave_readdata    (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_readdata),    //                        .readdata
		.DEBUG_avalon_jtag_slave_write_n     (~mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_write),      //                        .write_n
		.DEBUG_avalon_jtag_slave_writedata   (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_writedata),   //                        .writedata
		.DEBUG_avalon_jtag_slave_waitrequest (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_waitrequest), //                        .waitrequest
		.DEBUG_irq_irq                       (irq_mapper_receiver0_irq),                                                //               DEBUG_irq.irq
		.SRAM_s1_address                     (mm_interconnect_0_mem_sys_subsystem_sram_s1_address),                     //                 SRAM_s1.address
		.SRAM_s1_clken                       (mm_interconnect_0_mem_sys_subsystem_sram_s1_clken),                       //                        .clken
		.SRAM_s1_chipselect                  (mm_interconnect_0_mem_sys_subsystem_sram_s1_chipselect),                  //                        .chipselect
		.SRAM_s1_write                       (mm_interconnect_0_mem_sys_subsystem_sram_s1_write),                       //                        .write
		.SRAM_s1_readdata                    (mm_interconnect_0_mem_sys_subsystem_sram_s1_readdata),                    //                        .readdata
		.SRAM_s1_writedata                   (mm_interconnect_0_mem_sys_subsystem_sram_s1_writedata),                   //                        .writedata
		.SRAM_s1_byteenable                  (mm_interconnect_0_mem_sys_subsystem_sram_s1_byteenable),                  //                        .byteenable
		.SYS_ID_control_slave_readdata       (mm_interconnect_0_mem_sys_subsystem_sys_id_control_slave_readdata),       //    SYS_ID_control_slave.readdata
		.SYS_ID_control_slave_address        (mm_interconnect_0_mem_sys_subsystem_sys_id_control_slave_address),        //                        .address
		.clk_clk                             (clk_clk),                                                                 //                     clk.clk
		.reset_reset                         (rst_controller_001_reset_out_reset)                                       //                   reset.reset
	);

	avalon_design_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                                         (clk_clk),                                                                 //                                     clk_0_clk.clk
		.mem_sys_subsystem_reset_reset_bridge_in_reset_reset   (rst_controller_001_reset_out_reset),                                      // mem_sys_subsystem_reset_reset_bridge_in_reset.reset
		.NIOS_II_reset_reset_bridge_in_reset_reset             (rst_controller_reset_out_reset),                                          //           NIOS_II_reset_reset_bridge_in_reset.reset
		.NIOS_II_data_master_address                           (nios_ii_data_master_address),                                             //                           NIOS_II_data_master.address
		.NIOS_II_data_master_waitrequest                       (nios_ii_data_master_waitrequest),                                         //                                              .waitrequest
		.NIOS_II_data_master_byteenable                        (nios_ii_data_master_byteenable),                                          //                                              .byteenable
		.NIOS_II_data_master_read                              (nios_ii_data_master_read),                                                //                                              .read
		.NIOS_II_data_master_readdata                          (nios_ii_data_master_readdata),                                            //                                              .readdata
		.NIOS_II_data_master_readdatavalid                     (nios_ii_data_master_readdatavalid),                                       //                                              .readdatavalid
		.NIOS_II_data_master_write                             (nios_ii_data_master_write),                                               //                                              .write
		.NIOS_II_data_master_writedata                         (nios_ii_data_master_writedata),                                           //                                              .writedata
		.NIOS_II_data_master_debugaccess                       (nios_ii_data_master_debugaccess),                                         //                                              .debugaccess
		.NIOS_II_instruction_master_address                    (nios_ii_instruction_master_address),                                      //                    NIOS_II_instruction_master.address
		.NIOS_II_instruction_master_waitrequest                (nios_ii_instruction_master_waitrequest),                                  //                                              .waitrequest
		.NIOS_II_instruction_master_read                       (nios_ii_instruction_master_read),                                         //                                              .read
		.NIOS_II_instruction_master_readdata                   (nios_ii_instruction_master_readdata),                                     //                                              .readdata
		.NIOS_II_instruction_master_readdatavalid              (nios_ii_instruction_master_readdatavalid),                                //                                              .readdatavalid
		.io_peripherals_s0_address                             (mm_interconnect_0_io_peripherals_s0_address),                             //                             io_peripherals_s0.address
		.io_peripherals_s0_write                               (mm_interconnect_0_io_peripherals_s0_write),                               //                                              .write
		.io_peripherals_s0_read                                (mm_interconnect_0_io_peripherals_s0_read),                                //                                              .read
		.io_peripherals_s0_readdata                            (mm_interconnect_0_io_peripherals_s0_readdata),                            //                                              .readdata
		.io_peripherals_s0_writedata                           (mm_interconnect_0_io_peripherals_s0_writedata),                           //                                              .writedata
		.io_peripherals_s0_burstcount                          (mm_interconnect_0_io_peripherals_s0_burstcount),                          //                                              .burstcount
		.io_peripherals_s0_byteenable                          (mm_interconnect_0_io_peripherals_s0_byteenable),                          //                                              .byteenable
		.io_peripherals_s0_readdatavalid                       (mm_interconnect_0_io_peripherals_s0_readdatavalid),                       //                                              .readdatavalid
		.io_peripherals_s0_waitrequest                         (mm_interconnect_0_io_peripherals_s0_waitrequest),                         //                                              .waitrequest
		.io_peripherals_s0_debugaccess                         (mm_interconnect_0_io_peripherals_s0_debugaccess),                         //                                              .debugaccess
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_address     (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_address),     //     mem_sys_subsystem_DEBUG_avalon_jtag_slave.address
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_write       (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_write),       //                                              .write
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_read        (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_read),        //                                              .read
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_readdata    (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_readdata),    //                                              .readdata
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_writedata   (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_writedata),   //                                              .writedata
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_waitrequest (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_waitrequest), //                                              .waitrequest
		.mem_sys_subsystem_DEBUG_avalon_jtag_slave_chipselect  (mm_interconnect_0_mem_sys_subsystem_debug_avalon_jtag_slave_chipselect),  //                                              .chipselect
		.mem_sys_subsystem_SRAM_s1_address                     (mm_interconnect_0_mem_sys_subsystem_sram_s1_address),                     //                     mem_sys_subsystem_SRAM_s1.address
		.mem_sys_subsystem_SRAM_s1_write                       (mm_interconnect_0_mem_sys_subsystem_sram_s1_write),                       //                                              .write
		.mem_sys_subsystem_SRAM_s1_readdata                    (mm_interconnect_0_mem_sys_subsystem_sram_s1_readdata),                    //                                              .readdata
		.mem_sys_subsystem_SRAM_s1_writedata                   (mm_interconnect_0_mem_sys_subsystem_sram_s1_writedata),                   //                                              .writedata
		.mem_sys_subsystem_SRAM_s1_byteenable                  (mm_interconnect_0_mem_sys_subsystem_sram_s1_byteenable),                  //                                              .byteenable
		.mem_sys_subsystem_SRAM_s1_chipselect                  (mm_interconnect_0_mem_sys_subsystem_sram_s1_chipselect),                  //                                              .chipselect
		.mem_sys_subsystem_SRAM_s1_clken                       (mm_interconnect_0_mem_sys_subsystem_sram_s1_clken),                       //                                              .clken
		.mem_sys_subsystem_SYS_ID_control_slave_address        (mm_interconnect_0_mem_sys_subsystem_sys_id_control_slave_address),        //        mem_sys_subsystem_SYS_ID_control_slave.address
		.mem_sys_subsystem_SYS_ID_control_slave_readdata       (mm_interconnect_0_mem_sys_subsystem_sys_id_control_slave_readdata),       //                                              .readdata
		.NIOS_II_debug_mem_slave_address                       (mm_interconnect_0_nios_ii_debug_mem_slave_address),                       //                       NIOS_II_debug_mem_slave.address
		.NIOS_II_debug_mem_slave_write                         (mm_interconnect_0_nios_ii_debug_mem_slave_write),                         //                                              .write
		.NIOS_II_debug_mem_slave_read                          (mm_interconnect_0_nios_ii_debug_mem_slave_read),                          //                                              .read
		.NIOS_II_debug_mem_slave_readdata                      (mm_interconnect_0_nios_ii_debug_mem_slave_readdata),                      //                                              .readdata
		.NIOS_II_debug_mem_slave_writedata                     (mm_interconnect_0_nios_ii_debug_mem_slave_writedata),                     //                                              .writedata
		.NIOS_II_debug_mem_slave_byteenable                    (mm_interconnect_0_nios_ii_debug_mem_slave_byteenable),                    //                                              .byteenable
		.NIOS_II_debug_mem_slave_waitrequest                   (mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest),                   //                                              .waitrequest
		.NIOS_II_debug_mem_slave_debugaccess                   (mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess)                    //                                              .debugaccess
	);

	avalon_design_irq_mapper irq_mapper (
		.clk           (clk_clk),                        //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (nios_ii_irq_irq)                 //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (nios_ii_debug_reset_request_reset),  // reset_in0.reset
		.reset_in1      (nios_ii_debug_reset_request_reset),  // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (nios_ii_debug_reset_request_reset),  // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
