// avalon_design_DSP_NIOS.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module avalon_design_DSP_NIOS (
		input  wire        clk_clk,          //   clk.clk
		input  wire        reset_reset,      // reset.reset
		output wire        s0_waitrequest,   //    s0.waitrequest
		output wire [31:0] s0_readdata,      //      .readdata
		output wire        s0_readdatavalid, //      .readdatavalid
		input  wire [0:0]  s0_burstcount,    //      .burstcount
		input  wire [31:0] s0_writedata,     //      .writedata
		input  wire [9:0]  s0_address,       //      .address
		input  wire        s0_write,         //      .write
		input  wire        s0_read,          //      .read
		input  wire [3:0]  s0_byteenable,    //      .byteenable
		input  wire        s0_debugaccess    //      .debugaccess
	);

	wire         peripheral_bridge_m0_waitrequest;             // mm_interconnect_0:peripheral_bridge_m0_waitrequest -> peripheral_bridge:m0_waitrequest
	wire  [31:0] peripheral_bridge_m0_readdata;                // mm_interconnect_0:peripheral_bridge_m0_readdata -> peripheral_bridge:m0_readdata
	wire         peripheral_bridge_m0_debugaccess;             // peripheral_bridge:m0_debugaccess -> mm_interconnect_0:peripheral_bridge_m0_debugaccess
	wire   [9:0] peripheral_bridge_m0_address;                 // peripheral_bridge:m0_address -> mm_interconnect_0:peripheral_bridge_m0_address
	wire         peripheral_bridge_m0_read;                    // peripheral_bridge:m0_read -> mm_interconnect_0:peripheral_bridge_m0_read
	wire   [3:0] peripheral_bridge_m0_byteenable;              // peripheral_bridge:m0_byteenable -> mm_interconnect_0:peripheral_bridge_m0_byteenable
	wire         peripheral_bridge_m0_readdatavalid;           // mm_interconnect_0:peripheral_bridge_m0_readdatavalid -> peripheral_bridge:m0_readdatavalid
	wire  [31:0] peripheral_bridge_m0_writedata;               // peripheral_bridge:m0_writedata -> mm_interconnect_0:peripheral_bridge_m0_writedata
	wire         peripheral_bridge_m0_write;                   // peripheral_bridge:m0_write -> mm_interconnect_0:peripheral_bridge_m0_write
	wire   [0:0] peripheral_bridge_m0_burstcount;              // peripheral_bridge:m0_burstcount -> mm_interconnect_0:peripheral_bridge_m0_burstcount
	wire         mm_interconnect_0_fifo_in_in_waitrequest;     // FIFO_IN:avalonmm_write_slave_waitrequest -> mm_interconnect_0:FIFO_IN_in_waitrequest
	wire   [0:0] mm_interconnect_0_fifo_in_in_address;         // mm_interconnect_0:FIFO_IN_in_address -> FIFO_IN:avalonmm_write_slave_address
	wire         mm_interconnect_0_fifo_in_in_write;           // mm_interconnect_0:FIFO_IN_in_write -> FIFO_IN:avalonmm_write_slave_write
	wire  [31:0] mm_interconnect_0_fifo_in_in_writedata;       // mm_interconnect_0:FIFO_IN_in_writedata -> FIFO_IN:avalonmm_write_slave_writedata
	wire  [31:0] mm_interconnect_0_fifo_in_in_csr_readdata;    // FIFO_IN:wrclk_control_slave_readdata -> mm_interconnect_0:FIFO_IN_in_csr_readdata
	wire   [2:0] mm_interconnect_0_fifo_in_in_csr_address;     // mm_interconnect_0:FIFO_IN_in_csr_address -> FIFO_IN:wrclk_control_slave_address
	wire         mm_interconnect_0_fifo_in_in_csr_read;        // mm_interconnect_0:FIFO_IN_in_csr_read -> FIFO_IN:wrclk_control_slave_read
	wire         mm_interconnect_0_fifo_in_in_csr_write;       // mm_interconnect_0:FIFO_IN_in_csr_write -> FIFO_IN:wrclk_control_slave_write
	wire  [31:0] mm_interconnect_0_fifo_in_in_csr_writedata;   // mm_interconnect_0:FIFO_IN_in_csr_writedata -> FIFO_IN:wrclk_control_slave_writedata
	wire  [31:0] mm_interconnect_0_fifo_out_out_readdata;      // FIFO_OUT:avalonmm_read_slave_readdata -> mm_interconnect_0:FIFO_OUT_out_readdata
	wire         mm_interconnect_0_fifo_out_out_waitrequest;   // FIFO_OUT:avalonmm_read_slave_waitrequest -> mm_interconnect_0:FIFO_OUT_out_waitrequest
	wire   [0:0] mm_interconnect_0_fifo_out_out_address;       // mm_interconnect_0:FIFO_OUT_out_address -> FIFO_OUT:avalonmm_read_slave_address
	wire         mm_interconnect_0_fifo_out_out_read;          // mm_interconnect_0:FIFO_OUT_out_read -> FIFO_OUT:avalonmm_read_slave_read
	wire  [31:0] mm_interconnect_0_fifo_out_out_csr_readdata;  // FIFO_OUT:rdclk_control_slave_readdata -> mm_interconnect_0:FIFO_OUT_out_csr_readdata
	wire   [2:0] mm_interconnect_0_fifo_out_out_csr_address;   // mm_interconnect_0:FIFO_OUT_out_csr_address -> FIFO_OUT:rdclk_control_slave_address
	wire         mm_interconnect_0_fifo_out_out_csr_read;      // mm_interconnect_0:FIFO_OUT_out_csr_read -> FIFO_OUT:rdclk_control_slave_read
	wire         mm_interconnect_0_fifo_out_out_csr_write;     // mm_interconnect_0:FIFO_OUT_out_csr_write -> FIFO_OUT:rdclk_control_slave_write
	wire  [31:0] mm_interconnect_0_fifo_out_out_csr_writedata; // mm_interconnect_0:FIFO_OUT_out_csr_writedata -> FIFO_OUT:rdclk_control_slave_writedata
	wire         fifo_in_out_valid;                            // FIFO_IN:avalonst_source_valid -> avalon_st_adapter:in_0_valid
	wire  [24:0] fifo_in_out_data;                             // FIFO_IN:avalonst_source_data -> avalon_st_adapter:in_0_data
	wire         fifo_in_out_ready;                            // avalon_st_adapter:in_0_ready -> FIFO_IN:avalonst_source_ready
	wire         fifo_in_out_startofpacket;                    // FIFO_IN:avalonst_source_startofpacket -> avalon_st_adapter:in_0_startofpacket
	wire         fifo_in_out_endofpacket;                      // FIFO_IN:avalonst_source_endofpacket -> avalon_st_adapter:in_0_endofpacket
	wire         avalon_st_adapter_out_0_valid;                // avalon_st_adapter:out_0_valid -> FFT_IP:sink_valid
	wire  [24:0] avalon_st_adapter_out_0_data;                 // avalon_st_adapter:out_0_data -> FFT_IP:sink_data
	wire         avalon_st_adapter_out_0_ready;                // FFT_IP:sink_ready -> avalon_st_adapter:out_0_ready
	wire         avalon_st_adapter_out_0_startofpacket;        // avalon_st_adapter:out_0_startofpacket -> FFT_IP:sink_sop
	wire         avalon_st_adapter_out_0_endofpacket;          // avalon_st_adapter:out_0_endofpacket -> FFT_IP:sink_eop
	wire   [1:0] avalon_st_adapter_out_0_error;                // avalon_st_adapter:out_0_error -> FFT_IP:sink_error
	wire         fft_ip_source_valid;                          // FFT_IP:source_valid -> avalon_st_adapter_001:in_0_valid
	wire  [29:0] fft_ip_source_data;                           // FFT_IP:source_data -> avalon_st_adapter_001:in_0_data
	wire         fft_ip_source_ready;                          // avalon_st_adapter_001:in_0_ready -> FFT_IP:source_ready
	wire         fft_ip_source_startofpacket;                  // FFT_IP:source_sop -> avalon_st_adapter_001:in_0_startofpacket
	wire   [1:0] fft_ip_source_error;                          // FFT_IP:source_error -> avalon_st_adapter_001:in_0_error
	wire         fft_ip_source_endofpacket;                    // FFT_IP:source_eop -> avalon_st_adapter_001:in_0_endofpacket
	wire         avalon_st_adapter_001_out_0_valid;            // avalon_st_adapter_001:out_0_valid -> FIFO_OUT:avalonst_sink_valid
	wire  [29:0] avalon_st_adapter_001_out_0_data;             // avalon_st_adapter_001:out_0_data -> FIFO_OUT:avalonst_sink_data
	wire         avalon_st_adapter_001_out_0_ready;            // FIFO_OUT:avalonst_sink_ready -> avalon_st_adapter_001:out_0_ready
	wire         avalon_st_adapter_001_out_0_startofpacket;    // avalon_st_adapter_001:out_0_startofpacket -> FIFO_OUT:avalonst_sink_startofpacket
	wire         avalon_st_adapter_001_out_0_endofpacket;      // avalon_st_adapter_001:out_0_endofpacket -> FIFO_OUT:avalonst_sink_endofpacket
	wire  [11:0] fft_ip_source_imag;                           // port fragment
	wire  [11:0] fft_ip_source_real;                           // port fragment
	wire   [5:0] fft_ip_source_exp;                            // port fragment

	avalon_design_DSP_NIOS_FFT_IP fft_ip (
		.clk          (clk_clk),                               //    clk.clk
		.reset_n      (~reset_reset),                          //    rst.reset_n
		.sink_valid   (avalon_st_adapter_out_0_valid),         //   sink.valid
		.sink_ready   (avalon_st_adapter_out_0_ready),         //       .ready
		.sink_error   (avalon_st_adapter_out_0_error),         //       .error
		.sink_sop     (avalon_st_adapter_out_0_startofpacket), //       .startofpacket
		.sink_eop     (avalon_st_adapter_out_0_endofpacket),   //       .endofpacket
		.sink_real    (avalon_st_adapter_out_0_data[24:13]),   //       .data
		.sink_imag    (avalon_st_adapter_out_0_data[12:1]),    //       .data
		.inverse      (avalon_st_adapter_out_0_data[0]),       //       .data
		.source_valid (fft_ip_source_valid),                   // source.valid
		.source_ready (fft_ip_source_ready),                   //       .ready
		.source_error (fft_ip_source_error),                   //       .error
		.source_sop   (fft_ip_source_startofpacket),           //       .startofpacket
		.source_eop   (fft_ip_source_endofpacket),             //       .endofpacket
		.source_real  (fft_ip_source_real[11:0]),              //       .data
		.source_imag  (fft_ip_source_imag[11:0]),              //       .data
		.source_exp   (fft_ip_source_exp[5:0])                 //       .data
	);

	avalon_design_DSP_NIOS_FIFO_IN fifo_in (
		.wrclock                          (clk_clk),                                    //    clk_in.clk
		.wrreset_n                        (~reset_reset),                               //  reset_in.reset_n
		.rdclock                          (clk_clk),                                    //   clk_out.clk
		.rdreset_n                        (~reset_reset),                               // reset_out.reset_n
		.avalonmm_write_slave_writedata   (mm_interconnect_0_fifo_in_in_writedata),     //        in.writedata
		.avalonmm_write_slave_write       (mm_interconnect_0_fifo_in_in_write),         //          .write
		.avalonmm_write_slave_address     (mm_interconnect_0_fifo_in_in_address),       //          .address
		.avalonmm_write_slave_waitrequest (mm_interconnect_0_fifo_in_in_waitrequest),   //          .waitrequest
		.avalonst_source_valid            (fifo_in_out_valid),                          //       out.valid
		.avalonst_source_data             (fifo_in_out_data),                           //          .data
		.avalonst_source_startofpacket    (fifo_in_out_startofpacket),                  //          .startofpacket
		.avalonst_source_endofpacket      (fifo_in_out_endofpacket),                    //          .endofpacket
		.avalonst_source_ready            (fifo_in_out_ready),                          //          .ready
		.wrclk_control_slave_address      (mm_interconnect_0_fifo_in_in_csr_address),   //    in_csr.address
		.wrclk_control_slave_read         (mm_interconnect_0_fifo_in_in_csr_read),      //          .read
		.wrclk_control_slave_writedata    (mm_interconnect_0_fifo_in_in_csr_writedata), //          .writedata
		.wrclk_control_slave_write        (mm_interconnect_0_fifo_in_in_csr_write),     //          .write
		.wrclk_control_slave_readdata     (mm_interconnect_0_fifo_in_in_csr_readdata)   //          .readdata
	);

	avalon_design_DSP_NIOS_FIFO_OUT fifo_out (
		.wrclock                         (clk_clk),                                      //    clk_in.clk
		.wrreset_n                       (~reset_reset),                                 //  reset_in.reset_n
		.rdclock                         (clk_clk),                                      //   clk_out.clk
		.rdreset_n                       (~reset_reset),                                 // reset_out.reset_n
		.avalonst_sink_valid             (avalon_st_adapter_001_out_0_valid),            //        in.valid
		.avalonst_sink_data              (avalon_st_adapter_001_out_0_data),             //          .data
		.avalonst_sink_startofpacket     (avalon_st_adapter_001_out_0_startofpacket),    //          .startofpacket
		.avalonst_sink_endofpacket       (avalon_st_adapter_001_out_0_endofpacket),      //          .endofpacket
		.avalonst_sink_ready             (avalon_st_adapter_001_out_0_ready),            //          .ready
		.avalonmm_read_slave_readdata    (mm_interconnect_0_fifo_out_out_readdata),      //       out.readdata
		.avalonmm_read_slave_read        (mm_interconnect_0_fifo_out_out_read),          //          .read
		.avalonmm_read_slave_address     (mm_interconnect_0_fifo_out_out_address),       //          .address
		.avalonmm_read_slave_waitrequest (mm_interconnect_0_fifo_out_out_waitrequest),   //          .waitrequest
		.rdclk_control_slave_address     (mm_interconnect_0_fifo_out_out_csr_address),   //   out_csr.address
		.rdclk_control_slave_read        (mm_interconnect_0_fifo_out_out_csr_read),      //          .read
		.rdclk_control_slave_writedata   (mm_interconnect_0_fifo_out_out_csr_writedata), //          .writedata
		.rdclk_control_slave_write       (mm_interconnect_0_fifo_out_out_csr_write),     //          .write
		.rdclk_control_slave_readdata    (mm_interconnect_0_fifo_out_out_csr_readdata)   //          .readdata
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (10),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) peripheral_bridge (
		.clk              (clk_clk),                            //   clk.clk
		.reset            (reset_reset),                        // reset.reset
		.s0_waitrequest   (s0_waitrequest),                     //    s0.waitrequest
		.s0_readdata      (s0_readdata),                        //      .readdata
		.s0_readdatavalid (s0_readdatavalid),                   //      .readdatavalid
		.s0_burstcount    (s0_burstcount),                      //      .burstcount
		.s0_writedata     (s0_writedata),                       //      .writedata
		.s0_address       (s0_address),                         //      .address
		.s0_write         (s0_write),                           //      .write
		.s0_read          (s0_read),                            //      .read
		.s0_byteenable    (s0_byteenable),                      //      .byteenable
		.s0_debugaccess   (s0_debugaccess),                     //      .debugaccess
		.m0_waitrequest   (peripheral_bridge_m0_waitrequest),   //    m0.waitrequest
		.m0_readdata      (peripheral_bridge_m0_readdata),      //      .readdata
		.m0_readdatavalid (peripheral_bridge_m0_readdatavalid), //      .readdatavalid
		.m0_burstcount    (peripheral_bridge_m0_burstcount),    //      .burstcount
		.m0_writedata     (peripheral_bridge_m0_writedata),     //      .writedata
		.m0_address       (peripheral_bridge_m0_address),       //      .address
		.m0_write         (peripheral_bridge_m0_write),         //      .write
		.m0_read          (peripheral_bridge_m0_read),          //      .read
		.m0_byteenable    (peripheral_bridge_m0_byteenable),    //      .byteenable
		.m0_debugaccess   (peripheral_bridge_m0_debugaccess),   //      .debugaccess
		.s0_response      (),                                   // (terminated)
		.m0_response      (2'b00)                               // (terminated)
	);

	avalon_design_DSP_NIOS_mm_interconnect_0 mm_interconnect_0 (
		.clock_bridge_out_clk_clk                            (clk_clk),                                      //                          clock_bridge_out_clk.clk
		.peripheral_bridge_reset_reset_bridge_in_reset_reset (reset_reset),                                  // peripheral_bridge_reset_reset_bridge_in_reset.reset
		.peripheral_bridge_m0_address                        (peripheral_bridge_m0_address),                 //                          peripheral_bridge_m0.address
		.peripheral_bridge_m0_waitrequest                    (peripheral_bridge_m0_waitrequest),             //                                              .waitrequest
		.peripheral_bridge_m0_burstcount                     (peripheral_bridge_m0_burstcount),              //                                              .burstcount
		.peripheral_bridge_m0_byteenable                     (peripheral_bridge_m0_byteenable),              //                                              .byteenable
		.peripheral_bridge_m0_read                           (peripheral_bridge_m0_read),                    //                                              .read
		.peripheral_bridge_m0_readdata                       (peripheral_bridge_m0_readdata),                //                                              .readdata
		.peripheral_bridge_m0_readdatavalid                  (peripheral_bridge_m0_readdatavalid),           //                                              .readdatavalid
		.peripheral_bridge_m0_write                          (peripheral_bridge_m0_write),                   //                                              .write
		.peripheral_bridge_m0_writedata                      (peripheral_bridge_m0_writedata),               //                                              .writedata
		.peripheral_bridge_m0_debugaccess                    (peripheral_bridge_m0_debugaccess),             //                                              .debugaccess
		.FIFO_IN_in_address                                  (mm_interconnect_0_fifo_in_in_address),         //                                    FIFO_IN_in.address
		.FIFO_IN_in_write                                    (mm_interconnect_0_fifo_in_in_write),           //                                              .write
		.FIFO_IN_in_writedata                                (mm_interconnect_0_fifo_in_in_writedata),       //                                              .writedata
		.FIFO_IN_in_waitrequest                              (mm_interconnect_0_fifo_in_in_waitrequest),     //                                              .waitrequest
		.FIFO_IN_in_csr_address                              (mm_interconnect_0_fifo_in_in_csr_address),     //                                FIFO_IN_in_csr.address
		.FIFO_IN_in_csr_write                                (mm_interconnect_0_fifo_in_in_csr_write),       //                                              .write
		.FIFO_IN_in_csr_read                                 (mm_interconnect_0_fifo_in_in_csr_read),        //                                              .read
		.FIFO_IN_in_csr_readdata                             (mm_interconnect_0_fifo_in_in_csr_readdata),    //                                              .readdata
		.FIFO_IN_in_csr_writedata                            (mm_interconnect_0_fifo_in_in_csr_writedata),   //                                              .writedata
		.FIFO_OUT_out_address                                (mm_interconnect_0_fifo_out_out_address),       //                                  FIFO_OUT_out.address
		.FIFO_OUT_out_read                                   (mm_interconnect_0_fifo_out_out_read),          //                                              .read
		.FIFO_OUT_out_readdata                               (mm_interconnect_0_fifo_out_out_readdata),      //                                              .readdata
		.FIFO_OUT_out_waitrequest                            (mm_interconnect_0_fifo_out_out_waitrequest),   //                                              .waitrequest
		.FIFO_OUT_out_csr_address                            (mm_interconnect_0_fifo_out_out_csr_address),   //                              FIFO_OUT_out_csr.address
		.FIFO_OUT_out_csr_write                              (mm_interconnect_0_fifo_out_out_csr_write),     //                                              .write
		.FIFO_OUT_out_csr_read                               (mm_interconnect_0_fifo_out_out_csr_read),      //                                              .read
		.FIFO_OUT_out_csr_readdata                           (mm_interconnect_0_fifo_out_out_csr_readdata),  //                                              .readdata
		.FIFO_OUT_out_csr_writedata                          (mm_interconnect_0_fifo_out_out_csr_writedata)  //                                              .writedata
	);

	avalon_design_DSP_NIOS_avalon_st_adapter #(
		.inBitsPerSymbol (25),
		.inUsePackets    (1),
		.inDataWidth     (25),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (1),
		.outDataWidth    (25),
		.outChannelWidth (0),
		.outErrorWidth   (2),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk        (clk_clk),                               // in_clk_0.clk
		.in_rst_0_reset      (reset_reset),                           // in_rst_0.reset
		.in_0_data           (fifo_in_out_data),                      //     in_0.data
		.in_0_valid          (fifo_in_out_valid),                     //         .valid
		.in_0_ready          (fifo_in_out_ready),                     //         .ready
		.in_0_startofpacket  (fifo_in_out_startofpacket),             //         .startofpacket
		.in_0_endofpacket    (fifo_in_out_endofpacket),               //         .endofpacket
		.out_0_data          (avalon_st_adapter_out_0_data),          //    out_0.data
		.out_0_valid         (avalon_st_adapter_out_0_valid),         //         .valid
		.out_0_ready         (avalon_st_adapter_out_0_ready),         //         .ready
		.out_0_startofpacket (avalon_st_adapter_out_0_startofpacket), //         .startofpacket
		.out_0_endofpacket   (avalon_st_adapter_out_0_endofpacket),   //         .endofpacket
		.out_0_error         (avalon_st_adapter_out_0_error)          //         .error
	);

	avalon_design_DSP_NIOS_avalon_st_adapter_001 #(
		.inBitsPerSymbol (30),
		.inUsePackets    (1),
		.inDataWidth     (30),
		.inChannelWidth  (0),
		.inErrorWidth    (2),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (30),
		.outChannelWidth (0),
		.outErrorWidth   (0),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (1)
	) avalon_st_adapter_001 (
		.in_clk_0_clk        (clk_clk),                                   // in_clk_0.clk
		.in_rst_0_reset      (reset_reset),                               // in_rst_0.reset
		.in_0_data           (fft_ip_source_data),                        //     in_0.data
		.in_0_valid          (fft_ip_source_valid),                       //         .valid
		.in_0_ready          (fft_ip_source_ready),                       //         .ready
		.in_0_startofpacket  (fft_ip_source_startofpacket),               //         .startofpacket
		.in_0_endofpacket    (fft_ip_source_endofpacket),                 //         .endofpacket
		.in_0_error          (fft_ip_source_error),                       //         .error
		.out_0_data          (avalon_st_adapter_001_out_0_data),          //    out_0.data
		.out_0_valid         (avalon_st_adapter_001_out_0_valid),         //         .valid
		.out_0_ready         (avalon_st_adapter_001_out_0_ready),         //         .ready
		.out_0_startofpacket (avalon_st_adapter_001_out_0_startofpacket), //         .startofpacket
		.out_0_endofpacket   (avalon_st_adapter_001_out_0_endofpacket)    //         .endofpacket
	);

	assign fft_ip_source_data = { fft_ip_source_real[11:0], fft_ip_source_imag[11:0], fft_ip_source_exp[5:0] };

endmodule
