module signal_monitor (
    input  wire        clk_50,
    input  wire  [1:0] KEY,      // Pushbuttons (Active Low)
    input  wire  [9:0] SW,       // 10 Slide Switches
    output wire        fpga_led, // PLL Locked status

    // ---------------------------------------------------------
    // GPIO Header (JP1) - 36 Bidirectional Pins
    // ---------------------------------------------------------
    inout  wire [35:0] GPIO,
	 
    // 7-Segment Displays
    output wire  [7:0] HEX0,     
    output wire  [7:0] HEX1,
    output wire  [7:0] HEX2,
    output wire  [7:0] HEX3,
    output wire  [7:0] HEX4,
    output wire  [7:0] HEX5,

    // ---------------------------------------------------------
    // Physical SDRAM Pins
    // ---------------------------------------------------------
    output wire [12:0] DRAM_ADDR,
    output wire [1:0]  DRAM_BA,
    output wire        DRAM_CAS_N,
    output wire        DRAM_CKE,
    output wire        DRAM_CLK,
    output wire        DRAM_CS_N,
    inout  wire [15:0] DRAM_DQ,
    output wire        DRAM_LDQM,  // Lower byte mask
    output wire        DRAM_UDQM,  // Upper byte mask
    output wire        DRAM_RAS_N,
    output wire        DRAM_WE_N
);

    // Instantiate the Qsys system (signal_analyzer)
    signal_analyzer u0 (
        .clk_clk                         (clk_50),                 
        
        // GPIO Interface
        .gpio_interface_export           (GPIO),                   
        
        // 7-Segment Display Mapping
        .hex_interface_hex_0             (HEX0),
        .hex_interface_hex_1             (HEX1),
        .hex_interface_hex_2             (HEX2),
        .hex_interface_hex_3             (HEX3),
        .hex_interface_hex_4             (HEX4),
        .hex_interface_hex_5             (HEX5),

        // Key and Switch Interface Mapping
        // These names are generated by Qsys for your conduit signals
        .key_interface_export (KEY), 
        .sw_interface_export  (SW),

        // PLL Reset & Lock Signals
        .pll_areset_export               (~KEY[1]),                
        .pll_locked_export               (fpga_led),               

        // SDRAM Interface Mapping
        .sdram_clk_clk                   (DRAM_CLK),               
        .sdram_wire_addr                 (DRAM_ADDR),         
        .sdram_wire_ba                   (DRAM_BA),           
        .sdram_wire_cas_n                (DRAM_CAS_N),        
        .sdram_wire_cke                  (DRAM_CKE),          
        .sdram_wire_cs_n                 (DRAM_CS_N),         
        .sdram_wire_dq                   (DRAM_DQ),           
        
        // Concatenate Upper and Lower masks for the 2-bit Qsys bus
        .sdram_wire_dqm                  ({DRAM_UDQM, DRAM_LDQM}), 
        
        .sdram_wire_ras_n                (DRAM_RAS_N),        
        .sdram_wire_we_n                 (DRAM_WE_N)          
    );

endmodule