// peripheral_interface.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module peripheral_interface (
		input  wire       clk_clk,                     //                  clk.clk
		input  wire [3:0] full_adder_signals_fa_a,     //   full_adder_signals.fa_a
		input  wire [3:0] full_adder_signals_fa_b,     //                     .fa_b
		output wire [3:0] full_adder_signals_fa_sum,   //                     .fa_sum
		output wire       full_adder_signals_fa_carry, //                     .fa_carry
		input  wire [3:0] hex0_display_signals_input,  // hex0_display_signals.input
		output wire [7:0] hex0_display_signals_output, //                     .output
		input  wire [3:0] hex1_display_signals_input,  // hex1_display_signals.input
		output wire [7:0] hex1_display_signals_output, //                     .output
		input  wire       key_deboucer_signals_input,  // key_deboucer_signals.input
		output wire       key_deboucer_signals_output, //                     .output
		input  wire       reset_reset_n                //                reset.reset_n
	);

	full_adder_4bit full_adder_4bit_0 (
		.a     (full_adder_signals_fa_a),     // fa_signals.fa_a
		.b     (full_adder_signals_fa_b),     //           .fa_b
		.sum   (full_adder_signals_fa_sum),   //           .fa_sum
		.carry (full_adder_signals_fa_carry)  //           .fa_carry
	);

	HexDigit_Decoder hex_display_0 (
		.hex_input  (hex0_display_signals_input),  // hex_display.input
		.seg_output (hex0_display_signals_output)  //            .output
	);

	HexDigit_Decoder hex_display_1 (
		.hex_input  (hex1_display_signals_input),  // hex_display.input
		.seg_output (hex1_display_signals_output)  //            .output
	);

	key_debounce key_register_0 (
		.clk       (clk_clk),                     //         clock.clk
		.key_n     (key_deboucer_signals_input),  // key_debouncer.input
		.key_pulse (key_deboucer_signals_output)  //              .output
	);

endmodule
