// nios_interface.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module nios_interface (
		input  wire  button_external_export, // button_external.export
		input  wire  clk_clk,                //             clk.clk
		output wire  led_external_export     //    led_external.export
	);

	wire         nios_ii_debug_reset_request_reset;                     // NIOS_II:debug_reset_request -> [rst_controller:reset_in0, rst_controller_001:reset_in0, rst_controller_001:reset_in1]
	wire  [31:0] nios_ii_data_master_readdata;                          // mm_interconnect_0:NIOS_II_data_master_readdata -> NIOS_II:d_readdata
	wire         nios_ii_data_master_waitrequest;                       // mm_interconnect_0:NIOS_II_data_master_waitrequest -> NIOS_II:d_waitrequest
	wire         nios_ii_data_master_debugaccess;                       // NIOS_II:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOS_II_data_master_debugaccess
	wire  [24:0] nios_ii_data_master_address;                           // NIOS_II:d_address -> mm_interconnect_0:NIOS_II_data_master_address
	wire   [3:0] nios_ii_data_master_byteenable;                        // NIOS_II:d_byteenable -> mm_interconnect_0:NIOS_II_data_master_byteenable
	wire         nios_ii_data_master_read;                              // NIOS_II:d_read -> mm_interconnect_0:NIOS_II_data_master_read
	wire         nios_ii_data_master_readdatavalid;                     // mm_interconnect_0:NIOS_II_data_master_readdatavalid -> NIOS_II:d_readdatavalid
	wire         nios_ii_data_master_write;                             // NIOS_II:d_write -> mm_interconnect_0:NIOS_II_data_master_write
	wire  [31:0] nios_ii_data_master_writedata;                         // NIOS_II:d_writedata -> mm_interconnect_0:NIOS_II_data_master_writedata
	wire  [31:0] nios_ii_instruction_master_readdata;                   // mm_interconnect_0:NIOS_II_instruction_master_readdata -> NIOS_II:i_readdata
	wire         nios_ii_instruction_master_waitrequest;                // mm_interconnect_0:NIOS_II_instruction_master_waitrequest -> NIOS_II:i_waitrequest
	wire  [24:0] nios_ii_instruction_master_address;                    // NIOS_II:i_address -> mm_interconnect_0:NIOS_II_instruction_master_address
	wire         nios_ii_instruction_master_read;                       // NIOS_II:i_read -> mm_interconnect_0:NIOS_II_instruction_master_read
	wire         nios_ii_instruction_master_readdatavalid;              // mm_interconnect_0:NIOS_II_instruction_master_readdatavalid -> NIOS_II:i_readdatavalid
	wire         mm_interconnect_0_debug_avalon_jtag_slave_chipselect;  // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;    // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire         mm_interconnect_0_debug_avalon_jtag_slave_waitrequest; // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire   [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;     // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire         mm_interconnect_0_debug_avalon_jtag_slave_read;        // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire         mm_interconnect_0_debug_avalon_jtag_slave_write;       // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire  [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;   // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire  [31:0] mm_interconnect_0_sys_id_control_slave_readdata;       // SYS_ID:readdata -> mm_interconnect_0:SYS_ID_control_slave_readdata
	wire   [0:0] mm_interconnect_0_sys_id_control_slave_address;        // mm_interconnect_0:SYS_ID_control_slave_address -> SYS_ID:address
	wire  [31:0] mm_interconnect_0_nios_ii_debug_mem_slave_readdata;    // NIOS_II:debug_mem_slave_readdata -> mm_interconnect_0:NIOS_II_debug_mem_slave_readdata
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest; // NIOS_II:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOS_II_debug_mem_slave_waitrequest
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess; // mm_interconnect_0:NIOS_II_debug_mem_slave_debugaccess -> NIOS_II:debug_mem_slave_debugaccess
	wire   [8:0] mm_interconnect_0_nios_ii_debug_mem_slave_address;     // mm_interconnect_0:NIOS_II_debug_mem_slave_address -> NIOS_II:debug_mem_slave_address
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_read;        // mm_interconnect_0:NIOS_II_debug_mem_slave_read -> NIOS_II:debug_mem_slave_read
	wire   [3:0] mm_interconnect_0_nios_ii_debug_mem_slave_byteenable;  // mm_interconnect_0:NIOS_II_debug_mem_slave_byteenable -> NIOS_II:debug_mem_slave_byteenable
	wire         mm_interconnect_0_nios_ii_debug_mem_slave_write;       // mm_interconnect_0:NIOS_II_debug_mem_slave_write -> NIOS_II:debug_mem_slave_write
	wire  [31:0] mm_interconnect_0_nios_ii_debug_mem_slave_writedata;   // mm_interconnect_0:NIOS_II_debug_mem_slave_writedata -> NIOS_II:debug_mem_slave_writedata
	wire  [31:0] mm_interconnect_0_peripheral_bridge_s0_readdata;       // peripheral_bridge:s0_readdata -> mm_interconnect_0:peripheral_bridge_s0_readdata
	wire         mm_interconnect_0_peripheral_bridge_s0_waitrequest;    // peripheral_bridge:s0_waitrequest -> mm_interconnect_0:peripheral_bridge_s0_waitrequest
	wire         mm_interconnect_0_peripheral_bridge_s0_debugaccess;    // mm_interconnect_0:peripheral_bridge_s0_debugaccess -> peripheral_bridge:s0_debugaccess
	wire   [9:0] mm_interconnect_0_peripheral_bridge_s0_address;        // mm_interconnect_0:peripheral_bridge_s0_address -> peripheral_bridge:s0_address
	wire         mm_interconnect_0_peripheral_bridge_s0_read;           // mm_interconnect_0:peripheral_bridge_s0_read -> peripheral_bridge:s0_read
	wire   [3:0] mm_interconnect_0_peripheral_bridge_s0_byteenable;     // mm_interconnect_0:peripheral_bridge_s0_byteenable -> peripheral_bridge:s0_byteenable
	wire         mm_interconnect_0_peripheral_bridge_s0_readdatavalid;  // peripheral_bridge:s0_readdatavalid -> mm_interconnect_0:peripheral_bridge_s0_readdatavalid
	wire         mm_interconnect_0_peripheral_bridge_s0_write;          // mm_interconnect_0:peripheral_bridge_s0_write -> peripheral_bridge:s0_write
	wire  [31:0] mm_interconnect_0_peripheral_bridge_s0_writedata;      // mm_interconnect_0:peripheral_bridge_s0_writedata -> peripheral_bridge:s0_writedata
	wire   [0:0] mm_interconnect_0_peripheral_bridge_s0_burstcount;     // mm_interconnect_0:peripheral_bridge_s0_burstcount -> peripheral_bridge:s0_burstcount
	wire         mm_interconnect_0_sram_s1_chipselect;                  // mm_interconnect_0:SRAM_s1_chipselect -> SRAM:chipselect
	wire  [31:0] mm_interconnect_0_sram_s1_readdata;                    // SRAM:readdata -> mm_interconnect_0:SRAM_s1_readdata
	wire  [14:0] mm_interconnect_0_sram_s1_address;                     // mm_interconnect_0:SRAM_s1_address -> SRAM:address
	wire   [3:0] mm_interconnect_0_sram_s1_byteenable;                  // mm_interconnect_0:SRAM_s1_byteenable -> SRAM:byteenable
	wire         mm_interconnect_0_sram_s1_write;                       // mm_interconnect_0:SRAM_s1_write -> SRAM:write
	wire  [31:0] mm_interconnect_0_sram_s1_writedata;                   // mm_interconnect_0:SRAM_s1_writedata -> SRAM:writedata
	wire         mm_interconnect_0_sram_s1_clken;                       // mm_interconnect_0:SRAM_s1_clken -> SRAM:clken
	wire         peripheral_bridge_m0_waitrequest;                      // mm_interconnect_1:peripheral_bridge_m0_waitrequest -> peripheral_bridge:m0_waitrequest
	wire  [31:0] peripheral_bridge_m0_readdata;                         // mm_interconnect_1:peripheral_bridge_m0_readdata -> peripheral_bridge:m0_readdata
	wire         peripheral_bridge_m0_debugaccess;                      // peripheral_bridge:m0_debugaccess -> mm_interconnect_1:peripheral_bridge_m0_debugaccess
	wire   [9:0] peripheral_bridge_m0_address;                          // peripheral_bridge:m0_address -> mm_interconnect_1:peripheral_bridge_m0_address
	wire         peripheral_bridge_m0_read;                             // peripheral_bridge:m0_read -> mm_interconnect_1:peripheral_bridge_m0_read
	wire   [3:0] peripheral_bridge_m0_byteenable;                       // peripheral_bridge:m0_byteenable -> mm_interconnect_1:peripheral_bridge_m0_byteenable
	wire         peripheral_bridge_m0_readdatavalid;                    // mm_interconnect_1:peripheral_bridge_m0_readdatavalid -> peripheral_bridge:m0_readdatavalid
	wire  [31:0] peripheral_bridge_m0_writedata;                        // peripheral_bridge:m0_writedata -> mm_interconnect_1:peripheral_bridge_m0_writedata
	wire         peripheral_bridge_m0_write;                            // peripheral_bridge:m0_write -> mm_interconnect_1:peripheral_bridge_m0_write
	wire   [0:0] peripheral_bridge_m0_burstcount;                       // peripheral_bridge:m0_burstcount -> mm_interconnect_1:peripheral_bridge_m0_burstcount
	wire         mm_interconnect_1_led_pio_s1_chipselect;               // mm_interconnect_1:led_pio_s1_chipselect -> led_pio:chipselect
	wire  [31:0] mm_interconnect_1_led_pio_s1_readdata;                 // led_pio:readdata -> mm_interconnect_1:led_pio_s1_readdata
	wire   [2:0] mm_interconnect_1_led_pio_s1_address;                  // mm_interconnect_1:led_pio_s1_address -> led_pio:address
	wire         mm_interconnect_1_led_pio_s1_write;                    // mm_interconnect_1:led_pio_s1_write -> led_pio:write_n
	wire  [31:0] mm_interconnect_1_led_pio_s1_writedata;                // mm_interconnect_1:led_pio_s1_writedata -> led_pio:writedata
	wire  [31:0] mm_interconnect_1_button_pio_s1_readdata;              // button_pio:readdata -> mm_interconnect_1:button_pio_s1_readdata
	wire   [1:0] mm_interconnect_1_button_pio_s1_address;               // mm_interconnect_1:button_pio_s1_address -> button_pio:address
	wire         irq_mapper_receiver0_irq;                              // DEBUG:av_irq -> irq_mapper:receiver0_irq
	wire  [31:0] nios_ii_irq_irq;                                       // irq_mapper:sender_irq -> NIOS_II:irq
	wire         rst_controller_reset_out_reset;                        // rst_controller:reset_out -> [DEBUG:rst_n, SRAM:reset, SYS_ID:reset_n, button_pio:reset_n, led_pio:reset_n, mm_interconnect_0:DEBUG_reset_reset_bridge_in_reset_reset, mm_interconnect_1:peripheral_bridge_reset_reset_bridge_in_reset_reset, peripheral_bridge:reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                    // rst_controller:reset_req -> [SRAM:reset_req, rst_translator:reset_req_in]
	wire         rst_controller_001_reset_out_reset;                    // rst_controller_001:reset_out -> [NIOS_II:reset_n, irq_mapper:reset, mm_interconnect_0:NIOS_II_reset_reset_bridge_in_reset_reset]
	wire         rst_controller_001_reset_out_reset_req;                // rst_controller_001:reset_req -> [NIOS_II:reset_req, rst_translator_001:reset_req_in]

	nios_interface_DEBUG debug (
		.clk            (clk_clk),                                               //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver0_irq)                               //               irq.irq
	);

	nios_interface_NIOS_II nios_ii (
		.clk                                 (clk_clk),                                               //                       clk.clk
		.reset_n                             (~rst_controller_001_reset_out_reset),                   //                     reset.reset_n
		.reset_req                           (rst_controller_001_reset_out_reset_req),                //                          .reset_req
		.d_address                           (nios_ii_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios_ii_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios_ii_data_master_read),                              //                          .read
		.d_readdata                          (nios_ii_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios_ii_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios_ii_data_master_write),                             //                          .write
		.d_writedata                         (nios_ii_data_master_writedata),                         //                          .writedata
		.d_readdatavalid                     (nios_ii_data_master_readdatavalid),                     //                          .readdatavalid
		.debug_mem_slave_debugaccess_to_roms (nios_ii_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios_ii_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios_ii_instruction_master_read),                       //                          .read
		.i_readdata                          (nios_ii_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios_ii_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (nios_ii_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (nios_ii_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios_ii_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios_ii_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios_ii_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios_ii_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios_ii_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios_ii_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios_ii_debug_mem_slave_writedata),   //                          .writedata
		.dummy_ci_port                       ()                                                       // custom_instruction_master.readra
	);

	nios_interface_SRAM sram (
		.clk        (clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_sram_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_sram_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_sram_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_sram_s1_write),      //       .write
		.readdata   (mm_interconnect_0_sram_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_sram_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_sram_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),       // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req),   //       .reset_req
		.freeze     (1'b0)                                  // (terminated)
	);

	nios_interface_SYS_ID sys_id (
		.clock    (clk_clk),                                         //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                 //         reset.reset_n
		.readdata (mm_interconnect_0_sys_id_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sys_id_control_slave_address)   //              .address
	);

	nios_interface_button_pio button_pio (
		.clk      (clk_clk),                                  //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_1_button_pio_s1_address),  //                  s1.address
		.readdata (mm_interconnect_1_button_pio_s1_readdata), //                    .readdata
		.in_port  (button_external_export)                    // external_connection.export
	);

	nios_interface_led_pio led_pio (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address    (mm_interconnect_1_led_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_1_led_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_1_led_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_1_led_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_1_led_pio_s1_readdata),   //                    .readdata
		.out_port   (led_external_export)                      // external_connection.export
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (10),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) peripheral_bridge (
		.clk              (clk_clk),                                              //   clk.clk
		.reset            (rst_controller_reset_out_reset),                       // reset.reset
		.s0_waitrequest   (mm_interconnect_0_peripheral_bridge_s0_waitrequest),   //    s0.waitrequest
		.s0_readdata      (mm_interconnect_0_peripheral_bridge_s0_readdata),      //      .readdata
		.s0_readdatavalid (mm_interconnect_0_peripheral_bridge_s0_readdatavalid), //      .readdatavalid
		.s0_burstcount    (mm_interconnect_0_peripheral_bridge_s0_burstcount),    //      .burstcount
		.s0_writedata     (mm_interconnect_0_peripheral_bridge_s0_writedata),     //      .writedata
		.s0_address       (mm_interconnect_0_peripheral_bridge_s0_address),       //      .address
		.s0_write         (mm_interconnect_0_peripheral_bridge_s0_write),         //      .write
		.s0_read          (mm_interconnect_0_peripheral_bridge_s0_read),          //      .read
		.s0_byteenable    (mm_interconnect_0_peripheral_bridge_s0_byteenable),    //      .byteenable
		.s0_debugaccess   (mm_interconnect_0_peripheral_bridge_s0_debugaccess),   //      .debugaccess
		.m0_waitrequest   (peripheral_bridge_m0_waitrequest),                     //    m0.waitrequest
		.m0_readdata      (peripheral_bridge_m0_readdata),                        //      .readdata
		.m0_readdatavalid (peripheral_bridge_m0_readdatavalid),                   //      .readdatavalid
		.m0_burstcount    (peripheral_bridge_m0_burstcount),                      //      .burstcount
		.m0_writedata     (peripheral_bridge_m0_writedata),                       //      .writedata
		.m0_address       (peripheral_bridge_m0_address),                         //      .address
		.m0_write         (peripheral_bridge_m0_write),                           //      .write
		.m0_read          (peripheral_bridge_m0_read),                            //      .read
		.m0_byteenable    (peripheral_bridge_m0_byteenable),                      //      .byteenable
		.m0_debugaccess   (peripheral_bridge_m0_debugaccess),                     //      .debugaccess
		.s0_response      (),                                                     // (terminated)
		.m0_response      (2'b00)                                                 // (terminated)
	);

	nios_interface_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                             (clk_clk),                                               //                           clk_0_clk.clk
		.DEBUG_reset_reset_bridge_in_reset_reset   (rst_controller_reset_out_reset),                        //   DEBUG_reset_reset_bridge_in_reset.reset
		.NIOS_II_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                    // NIOS_II_reset_reset_bridge_in_reset.reset
		.NIOS_II_data_master_address               (nios_ii_data_master_address),                           //                 NIOS_II_data_master.address
		.NIOS_II_data_master_waitrequest           (nios_ii_data_master_waitrequest),                       //                                    .waitrequest
		.NIOS_II_data_master_byteenable            (nios_ii_data_master_byteenable),                        //                                    .byteenable
		.NIOS_II_data_master_read                  (nios_ii_data_master_read),                              //                                    .read
		.NIOS_II_data_master_readdata              (nios_ii_data_master_readdata),                          //                                    .readdata
		.NIOS_II_data_master_readdatavalid         (nios_ii_data_master_readdatavalid),                     //                                    .readdatavalid
		.NIOS_II_data_master_write                 (nios_ii_data_master_write),                             //                                    .write
		.NIOS_II_data_master_writedata             (nios_ii_data_master_writedata),                         //                                    .writedata
		.NIOS_II_data_master_debugaccess           (nios_ii_data_master_debugaccess),                       //                                    .debugaccess
		.NIOS_II_instruction_master_address        (nios_ii_instruction_master_address),                    //          NIOS_II_instruction_master.address
		.NIOS_II_instruction_master_waitrequest    (nios_ii_instruction_master_waitrequest),                //                                    .waitrequest
		.NIOS_II_instruction_master_read           (nios_ii_instruction_master_read),                       //                                    .read
		.NIOS_II_instruction_master_readdata       (nios_ii_instruction_master_readdata),                   //                                    .readdata
		.NIOS_II_instruction_master_readdatavalid  (nios_ii_instruction_master_readdatavalid),              //                                    .readdatavalid
		.DEBUG_avalon_jtag_slave_address           (mm_interconnect_0_debug_avalon_jtag_slave_address),     //             DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write             (mm_interconnect_0_debug_avalon_jtag_slave_write),       //                                    .write
		.DEBUG_avalon_jtag_slave_read              (mm_interconnect_0_debug_avalon_jtag_slave_read),        //                                    .read
		.DEBUG_avalon_jtag_slave_readdata          (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                                    .readdata
		.DEBUG_avalon_jtag_slave_writedata         (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                                    .writedata
		.DEBUG_avalon_jtag_slave_waitrequest       (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                                    .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect        (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  //                                    .chipselect
		.NIOS_II_debug_mem_slave_address           (mm_interconnect_0_nios_ii_debug_mem_slave_address),     //             NIOS_II_debug_mem_slave.address
		.NIOS_II_debug_mem_slave_write             (mm_interconnect_0_nios_ii_debug_mem_slave_write),       //                                    .write
		.NIOS_II_debug_mem_slave_read              (mm_interconnect_0_nios_ii_debug_mem_slave_read),        //                                    .read
		.NIOS_II_debug_mem_slave_readdata          (mm_interconnect_0_nios_ii_debug_mem_slave_readdata),    //                                    .readdata
		.NIOS_II_debug_mem_slave_writedata         (mm_interconnect_0_nios_ii_debug_mem_slave_writedata),   //                                    .writedata
		.NIOS_II_debug_mem_slave_byteenable        (mm_interconnect_0_nios_ii_debug_mem_slave_byteenable),  //                                    .byteenable
		.NIOS_II_debug_mem_slave_waitrequest       (mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest), //                                    .waitrequest
		.NIOS_II_debug_mem_slave_debugaccess       (mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess), //                                    .debugaccess
		.peripheral_bridge_s0_address              (mm_interconnect_0_peripheral_bridge_s0_address),        //                peripheral_bridge_s0.address
		.peripheral_bridge_s0_write                (mm_interconnect_0_peripheral_bridge_s0_write),          //                                    .write
		.peripheral_bridge_s0_read                 (mm_interconnect_0_peripheral_bridge_s0_read),           //                                    .read
		.peripheral_bridge_s0_readdata             (mm_interconnect_0_peripheral_bridge_s0_readdata),       //                                    .readdata
		.peripheral_bridge_s0_writedata            (mm_interconnect_0_peripheral_bridge_s0_writedata),      //                                    .writedata
		.peripheral_bridge_s0_burstcount           (mm_interconnect_0_peripheral_bridge_s0_burstcount),     //                                    .burstcount
		.peripheral_bridge_s0_byteenable           (mm_interconnect_0_peripheral_bridge_s0_byteenable),     //                                    .byteenable
		.peripheral_bridge_s0_readdatavalid        (mm_interconnect_0_peripheral_bridge_s0_readdatavalid),  //                                    .readdatavalid
		.peripheral_bridge_s0_waitrequest          (mm_interconnect_0_peripheral_bridge_s0_waitrequest),    //                                    .waitrequest
		.peripheral_bridge_s0_debugaccess          (mm_interconnect_0_peripheral_bridge_s0_debugaccess),    //                                    .debugaccess
		.SRAM_s1_address                           (mm_interconnect_0_sram_s1_address),                     //                             SRAM_s1.address
		.SRAM_s1_write                             (mm_interconnect_0_sram_s1_write),                       //                                    .write
		.SRAM_s1_readdata                          (mm_interconnect_0_sram_s1_readdata),                    //                                    .readdata
		.SRAM_s1_writedata                         (mm_interconnect_0_sram_s1_writedata),                   //                                    .writedata
		.SRAM_s1_byteenable                        (mm_interconnect_0_sram_s1_byteenable),                  //                                    .byteenable
		.SRAM_s1_chipselect                        (mm_interconnect_0_sram_s1_chipselect),                  //                                    .chipselect
		.SRAM_s1_clken                             (mm_interconnect_0_sram_s1_clken),                       //                                    .clken
		.SYS_ID_control_slave_address              (mm_interconnect_0_sys_id_control_slave_address),        //                SYS_ID_control_slave.address
		.SYS_ID_control_slave_readdata             (mm_interconnect_0_sys_id_control_slave_readdata)        //                                    .readdata
	);

	nios_interface_mm_interconnect_1 mm_interconnect_1 (
		.clk_0_clk_clk                                       (clk_clk),                                  //                                     clk_0_clk.clk
		.peripheral_bridge_reset_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),           // peripheral_bridge_reset_reset_bridge_in_reset.reset
		.peripheral_bridge_m0_address                        (peripheral_bridge_m0_address),             //                          peripheral_bridge_m0.address
		.peripheral_bridge_m0_waitrequest                    (peripheral_bridge_m0_waitrequest),         //                                              .waitrequest
		.peripheral_bridge_m0_burstcount                     (peripheral_bridge_m0_burstcount),          //                                              .burstcount
		.peripheral_bridge_m0_byteenable                     (peripheral_bridge_m0_byteenable),          //                                              .byteenable
		.peripheral_bridge_m0_read                           (peripheral_bridge_m0_read),                //                                              .read
		.peripheral_bridge_m0_readdata                       (peripheral_bridge_m0_readdata),            //                                              .readdata
		.peripheral_bridge_m0_readdatavalid                  (peripheral_bridge_m0_readdatavalid),       //                                              .readdatavalid
		.peripheral_bridge_m0_write                          (peripheral_bridge_m0_write),               //                                              .write
		.peripheral_bridge_m0_writedata                      (peripheral_bridge_m0_writedata),           //                                              .writedata
		.peripheral_bridge_m0_debugaccess                    (peripheral_bridge_m0_debugaccess),         //                                              .debugaccess
		.button_pio_s1_address                               (mm_interconnect_1_button_pio_s1_address),  //                                 button_pio_s1.address
		.button_pio_s1_readdata                              (mm_interconnect_1_button_pio_s1_readdata), //                                              .readdata
		.led_pio_s1_address                                  (mm_interconnect_1_led_pio_s1_address),     //                                    led_pio_s1.address
		.led_pio_s1_write                                    (mm_interconnect_1_led_pio_s1_write),       //                                              .write
		.led_pio_s1_readdata                                 (mm_interconnect_1_led_pio_s1_readdata),    //                                              .readdata
		.led_pio_s1_writedata                                (mm_interconnect_1_led_pio_s1_writedata),   //                                              .writedata
		.led_pio_s1_chipselect                               (mm_interconnect_1_led_pio_s1_chipselect)   //                                              .chipselect
	);

	nios_interface_irq_mapper irq_mapper (
		.clk           (clk_clk),                            //       clk.clk
		.reset         (rst_controller_001_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.sender_irq    (nios_ii_irq_irq)                     //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (nios_ii_debug_reset_request_reset),  // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (nios_ii_debug_reset_request_reset),      // reset_in0.reset
		.reset_in1      (nios_ii_debug_reset_request_reset),      // reset_in1.reset
		.clk            (clk_clk),                                //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

endmodule
