// avalon_design_io_peripherals.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module avalon_design_io_peripherals (
		input  wire [1:0]  button_interface_export, // button_interface.export
		input  wire        clk_clk,                 //              clk.clk
		output wire [7:0]  hex_interface_hex_0,     //    hex_interface.hex_0
		output wire [7:0]  hex_interface_hex_1,     //                 .hex_1
		output wire [7:0]  hex_interface_hex_2,     //                 .hex_2
		output wire [7:0]  hex_interface_hex_3,     //                 .hex_3
		output wire [7:0]  hex_interface_hex_4,     //                 .hex_4
		output wire [7:0]  hex_interface_hex_5,     //                 .hex_5
		output wire        led_interface_export,    //    led_interface.export
		input  wire        reset_reset,             //            reset.reset
		output wire        s0_waitrequest,          //               s0.waitrequest
		output wire [31:0] s0_readdata,             //                 .readdata
		output wire        s0_readdatavalid,        //                 .readdatavalid
		input  wire [0:0]  s0_burstcount,           //                 .burstcount
		input  wire [31:0] s0_writedata,            //                 .writedata
		input  wire [9:0]  s0_address,              //                 .address
		input  wire        s0_write,                //                 .write
		input  wire        s0_read,                 //                 .read
		input  wire [3:0]  s0_byteenable,           //                 .byteenable
		input  wire        s0_debugaccess           //                 .debugaccess
	);

	wire         peripheral_bridge_m0_waitrequest;           // mm_interconnect_0:peripheral_bridge_m0_waitrequest -> peripheral_bridge:m0_waitrequest
	wire  [31:0] peripheral_bridge_m0_readdata;              // mm_interconnect_0:peripheral_bridge_m0_readdata -> peripheral_bridge:m0_readdata
	wire         peripheral_bridge_m0_debugaccess;           // peripheral_bridge:m0_debugaccess -> mm_interconnect_0:peripheral_bridge_m0_debugaccess
	wire   [9:0] peripheral_bridge_m0_address;               // peripheral_bridge:m0_address -> mm_interconnect_0:peripheral_bridge_m0_address
	wire         peripheral_bridge_m0_read;                  // peripheral_bridge:m0_read -> mm_interconnect_0:peripheral_bridge_m0_read
	wire   [3:0] peripheral_bridge_m0_byteenable;            // peripheral_bridge:m0_byteenable -> mm_interconnect_0:peripheral_bridge_m0_byteenable
	wire         peripheral_bridge_m0_readdatavalid;         // mm_interconnect_0:peripheral_bridge_m0_readdatavalid -> peripheral_bridge:m0_readdatavalid
	wire  [31:0] peripheral_bridge_m0_writedata;             // peripheral_bridge:m0_writedata -> mm_interconnect_0:peripheral_bridge_m0_writedata
	wire         peripheral_bridge_m0_write;                 // peripheral_bridge:m0_write -> mm_interconnect_0:peripheral_bridge_m0_write
	wire   [0:0] peripheral_bridge_m0_burstcount;            // peripheral_bridge:m0_burstcount -> mm_interconnect_0:peripheral_bridge_m0_burstcount
	wire  [31:0] mm_interconnect_0_hex_display_s0_readdata;  // hex_display:avs_s0_readdata -> mm_interconnect_0:hex_display_s0_readdata
	wire   [0:0] mm_interconnect_0_hex_display_s0_address;   // mm_interconnect_0:hex_display_s0_address -> hex_display:avs_s0_address
	wire         mm_interconnect_0_hex_display_s0_read;      // mm_interconnect_0:hex_display_s0_read -> hex_display:avs_s0_read
	wire         mm_interconnect_0_hex_display_s0_write;     // mm_interconnect_0:hex_display_s0_write -> hex_display:avs_s0_write
	wire  [31:0] mm_interconnect_0_hex_display_s0_writedata; // mm_interconnect_0:hex_display_s0_writedata -> hex_display:avs_s0_writedata
	wire  [31:0] mm_interconnect_0_counter_s0_readdata;      // counter:avs_s0_readdata -> mm_interconnect_0:counter_s0_readdata
	wire   [1:0] mm_interconnect_0_counter_s0_address;       // mm_interconnect_0:counter_s0_address -> counter:avs_s0_address
	wire         mm_interconnect_0_counter_s0_read;          // mm_interconnect_0:counter_s0_read -> counter:avs_s0_read
	wire         mm_interconnect_0_counter_s0_write;         // mm_interconnect_0:counter_s0_write -> counter:avs_s0_write
	wire  [31:0] mm_interconnect_0_counter_s0_writedata;     // mm_interconnect_0:counter_s0_writedata -> counter:avs_s0_writedata
	wire         mm_interconnect_0_led_pio_s1_chipselect;    // mm_interconnect_0:led_pio_s1_chipselect -> led_pio:chipselect
	wire  [31:0] mm_interconnect_0_led_pio_s1_readdata;      // led_pio:readdata -> mm_interconnect_0:led_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_led_pio_s1_address;       // mm_interconnect_0:led_pio_s1_address -> led_pio:address
	wire         mm_interconnect_0_led_pio_s1_write;         // mm_interconnect_0:led_pio_s1_write -> led_pio:write_n
	wire  [31:0] mm_interconnect_0_led_pio_s1_writedata;     // mm_interconnect_0:led_pio_s1_writedata -> led_pio:writedata
	wire  [31:0] mm_interconnect_0_button_pio_s1_readdata;   // button_pio:readdata -> mm_interconnect_0:button_pio_s1_readdata
	wire   [1:0] mm_interconnect_0_button_pio_s1_address;    // mm_interconnect_0:button_pio_s1_address -> button_pio:address

	avalon_design_io_peripherals_button_pio button_pio (
		.clk      (clk_clk),                                  //                 clk.clk
		.reset_n  (~reset_reset),                             //               reset.reset_n
		.address  (mm_interconnect_0_button_pio_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_button_pio_s1_readdata), //                    .readdata
		.in_port  (button_interface_export)                   // external_connection.export
	);

	avalon_counter_logic #(
		.INITIAL_MAX_COUNT (34'b0000000000000000000000000001100100),
		.INITIAL_SPEED     (34'b0000000000010011000100101101000000)
	) counter (
		.clk              (clk_clk),                                // clock.clk
		.reset            (reset_reset),                            // reset.reset
		.avs_s0_address   (mm_interconnect_0_counter_s0_address),   //    s0.address
		.avs_s0_write     (mm_interconnect_0_counter_s0_write),     //      .write
		.avs_s0_writedata (mm_interconnect_0_counter_s0_writedata), //      .writedata
		.avs_s0_read      (mm_interconnect_0_counter_s0_read),      //      .read
		.avs_s0_readdata  (mm_interconnect_0_counter_s0_readdata)   //      .readdata
	);

	avalon_display_logic hex_display (
		.clk              (clk_clk),                                    //         clock.clk
		.reset            (reset_reset),                                //         reset.reset
		.avs_s0_address   (mm_interconnect_0_hex_display_s0_address),   //            s0.address
		.avs_s0_write     (mm_interconnect_0_hex_display_s0_write),     //              .write
		.avs_s0_writedata (mm_interconnect_0_hex_display_s0_writedata), //              .writedata
		.avs_s0_read      (mm_interconnect_0_hex_display_s0_read),      //              .read
		.avs_s0_readdata  (mm_interconnect_0_hex_display_s0_readdata),  //              .readdata
		.HEX0             (hex_interface_hex_0),                        // hex_interface.hex_0
		.HEX1             (hex_interface_hex_1),                        //              .hex_1
		.HEX2             (hex_interface_hex_2),                        //              .hex_2
		.HEX3             (hex_interface_hex_3),                        //              .hex_3
		.HEX4             (hex_interface_hex_4),                        //              .hex_4
		.HEX5             (hex_interface_hex_5)                         //              .hex_5
	);

	avalon_design_io_peripherals_led_pio led_pio (
		.clk        (clk_clk),                                 //                 clk.clk
		.reset_n    (~reset_reset),                            //               reset.reset_n
		.address    (mm_interconnect_0_led_pio_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_led_pio_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_led_pio_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_led_pio_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_led_pio_s1_readdata),   //                    .readdata
		.out_port   (led_interface_export)                     // external_connection.export
	);

	altera_avalon_mm_bridge #(
		.DATA_WIDTH        (32),
		.SYMBOL_WIDTH      (8),
		.HDL_ADDR_WIDTH    (10),
		.BURSTCOUNT_WIDTH  (1),
		.PIPELINE_COMMAND  (1),
		.PIPELINE_RESPONSE (1)
	) peripheral_bridge (
		.clk              (clk_clk),                            //   clk.clk
		.reset            (reset_reset),                        // reset.reset
		.s0_waitrequest   (s0_waitrequest),                     //    s0.waitrequest
		.s0_readdata      (s0_readdata),                        //      .readdata
		.s0_readdatavalid (s0_readdatavalid),                   //      .readdatavalid
		.s0_burstcount    (s0_burstcount),                      //      .burstcount
		.s0_writedata     (s0_writedata),                       //      .writedata
		.s0_address       (s0_address),                         //      .address
		.s0_write         (s0_write),                           //      .write
		.s0_read          (s0_read),                            //      .read
		.s0_byteenable    (s0_byteenable),                      //      .byteenable
		.s0_debugaccess   (s0_debugaccess),                     //      .debugaccess
		.m0_waitrequest   (peripheral_bridge_m0_waitrequest),   //    m0.waitrequest
		.m0_readdata      (peripheral_bridge_m0_readdata),      //      .readdata
		.m0_readdatavalid (peripheral_bridge_m0_readdatavalid), //      .readdatavalid
		.m0_burstcount    (peripheral_bridge_m0_burstcount),    //      .burstcount
		.m0_writedata     (peripheral_bridge_m0_writedata),     //      .writedata
		.m0_address       (peripheral_bridge_m0_address),       //      .address
		.m0_write         (peripheral_bridge_m0_write),         //      .write
		.m0_read          (peripheral_bridge_m0_read),          //      .read
		.m0_byteenable    (peripheral_bridge_m0_byteenable),    //      .byteenable
		.m0_debugaccess   (peripheral_bridge_m0_debugaccess),   //      .debugaccess
		.s0_response      (),                                   // (terminated)
		.m0_response      (2'b00)                               // (terminated)
	);

	avalon_design_io_peripherals_mm_interconnect_0 mm_interconnect_0 (
		.clock_bridge_out_clk_clk                            (clk_clk),                                    //                          clock_bridge_out_clk.clk
		.peripheral_bridge_reset_reset_bridge_in_reset_reset (reset_reset),                                // peripheral_bridge_reset_reset_bridge_in_reset.reset
		.peripheral_bridge_m0_address                        (peripheral_bridge_m0_address),               //                          peripheral_bridge_m0.address
		.peripheral_bridge_m0_waitrequest                    (peripheral_bridge_m0_waitrequest),           //                                              .waitrequest
		.peripheral_bridge_m0_burstcount                     (peripheral_bridge_m0_burstcount),            //                                              .burstcount
		.peripheral_bridge_m0_byteenable                     (peripheral_bridge_m0_byteenable),            //                                              .byteenable
		.peripheral_bridge_m0_read                           (peripheral_bridge_m0_read),                  //                                              .read
		.peripheral_bridge_m0_readdata                       (peripheral_bridge_m0_readdata),              //                                              .readdata
		.peripheral_bridge_m0_readdatavalid                  (peripheral_bridge_m0_readdatavalid),         //                                              .readdatavalid
		.peripheral_bridge_m0_write                          (peripheral_bridge_m0_write),                 //                                              .write
		.peripheral_bridge_m0_writedata                      (peripheral_bridge_m0_writedata),             //                                              .writedata
		.peripheral_bridge_m0_debugaccess                    (peripheral_bridge_m0_debugaccess),           //                                              .debugaccess
		.button_pio_s1_address                               (mm_interconnect_0_button_pio_s1_address),    //                                 button_pio_s1.address
		.button_pio_s1_readdata                              (mm_interconnect_0_button_pio_s1_readdata),   //                                              .readdata
		.counter_s0_address                                  (mm_interconnect_0_counter_s0_address),       //                                    counter_s0.address
		.counter_s0_write                                    (mm_interconnect_0_counter_s0_write),         //                                              .write
		.counter_s0_read                                     (mm_interconnect_0_counter_s0_read),          //                                              .read
		.counter_s0_readdata                                 (mm_interconnect_0_counter_s0_readdata),      //                                              .readdata
		.counter_s0_writedata                                (mm_interconnect_0_counter_s0_writedata),     //                                              .writedata
		.hex_display_s0_address                              (mm_interconnect_0_hex_display_s0_address),   //                                hex_display_s0.address
		.hex_display_s0_write                                (mm_interconnect_0_hex_display_s0_write),     //                                              .write
		.hex_display_s0_read                                 (mm_interconnect_0_hex_display_s0_read),      //                                              .read
		.hex_display_s0_readdata                             (mm_interconnect_0_hex_display_s0_readdata),  //                                              .readdata
		.hex_display_s0_writedata                            (mm_interconnect_0_hex_display_s0_writedata), //                                              .writedata
		.led_pio_s1_address                                  (mm_interconnect_0_led_pio_s1_address),       //                                    led_pio_s1.address
		.led_pio_s1_write                                    (mm_interconnect_0_led_pio_s1_write),         //                                              .write
		.led_pio_s1_readdata                                 (mm_interconnect_0_led_pio_s1_readdata),      //                                              .readdata
		.led_pio_s1_writedata                                (mm_interconnect_0_led_pio_s1_writedata),     //                                              .writedata
		.led_pio_s1_chipselect                               (mm_interconnect_0_led_pio_s1_chipselect)     //                                              .chipselect
	);

endmodule
