// avalon_design_mem_sys_subsystem.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module avalon_design_mem_sys_subsystem (
		input  wire        DEBUG_avalon_jtag_slave_chipselect,  // DEBUG_avalon_jtag_slave.chipselect
		input  wire        DEBUG_avalon_jtag_slave_address,     //                        .address
		input  wire        DEBUG_avalon_jtag_slave_read_n,      //                        .read_n
		output wire [31:0] DEBUG_avalon_jtag_slave_readdata,    //                        .readdata
		input  wire        DEBUG_avalon_jtag_slave_write_n,     //                        .write_n
		input  wire [31:0] DEBUG_avalon_jtag_slave_writedata,   //                        .writedata
		output wire        DEBUG_avalon_jtag_slave_waitrequest, //                        .waitrequest
		output wire        DEBUG_irq_irq,                       //               DEBUG_irq.irq
		input  wire [14:0] SRAM_s1_address,                     //                 SRAM_s1.address
		input  wire        SRAM_s1_clken,                       //                        .clken
		input  wire        SRAM_s1_chipselect,                  //                        .chipselect
		input  wire        SRAM_s1_write,                       //                        .write
		output wire [31:0] SRAM_s1_readdata,                    //                        .readdata
		input  wire [31:0] SRAM_s1_writedata,                   //                        .writedata
		input  wire [3:0]  SRAM_s1_byteenable,                  //                        .byteenable
		output wire [31:0] SYS_ID_control_slave_readdata,       //    SYS_ID_control_slave.readdata
		input  wire        SYS_ID_control_slave_address,        //                        .address
		input  wire        clk_clk,                             //                     clk.clk
		input  wire        reset_reset                          //                   reset.reset
	);

	wire    rst_controller_reset_out_reset;     // rst_controller:reset_out -> [DEBUG:rst_n, SRAM:reset, SYS_ID:reset_n]
	wire    rst_controller_reset_out_reset_req; // rst_controller:reset_req -> [SRAM:reset_req, rst_translator:reset_req_in]

	avalon_design_mem_sys_subsystem_DEBUG debug (
		.clk            (clk_clk),                             //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),     //             reset.reset_n
		.av_chipselect  (DEBUG_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (DEBUG_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (DEBUG_avalon_jtag_slave_read_n),      //                  .read_n
		.av_readdata    (DEBUG_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (DEBUG_avalon_jtag_slave_write_n),     //                  .write_n
		.av_writedata   (DEBUG_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (DEBUG_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (DEBUG_irq_irq)                        //               irq.irq
	);

	avalon_design_mem_sys_subsystem_SRAM sram (
		.clk        (clk_clk),                            //   clk1.clk
		.address    (SRAM_s1_address),                    //     s1.address
		.clken      (SRAM_s1_clken),                      //       .clken
		.chipselect (SRAM_s1_chipselect),                 //       .chipselect
		.write      (SRAM_s1_write),                      //       .write
		.readdata   (SRAM_s1_readdata),                   //       .readdata
		.writedata  (SRAM_s1_writedata),                  //       .writedata
		.byteenable (SRAM_s1_byteenable),                 //       .byteenable
		.reset      (rst_controller_reset_out_reset),     // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req), //       .reset_req
		.freeze     (1'b0)                                // (terminated)
	);

	avalon_design_mem_sys_subsystem_SYS_ID sys_id (
		.clock    (clk_clk),                         //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset), //         reset.reset_n
		.readdata (SYS_ID_control_slave_readdata),   // control_slave.readdata
		.address  (SYS_ID_control_slave_address)     //              .address
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (reset_reset),                        // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
