// signal_analyzer.v

// Generated using ACDS version 18.1 625

`timescale 1 ps / 1 ps
module signal_analyzer (
		input  wire        clk_clk,               //            clk.clk
		inout  wire [35:0] gpio_interface_export, // gpio_interface.export
		output wire [7:0]  hex_interface_hex_0,   //  hex_interface.hex_0
		output wire [7:0]  hex_interface_hex_1,   //               .hex_1
		output wire [7:0]  hex_interface_hex_2,   //               .hex_2
		output wire [7:0]  hex_interface_hex_3,   //               .hex_3
		output wire [7:0]  hex_interface_hex_4,   //               .hex_4
		output wire [7:0]  hex_interface_hex_5,   //               .hex_5
		input  wire [1:0]  key_interface_export,  //  key_interface.export
		input  wire        pll_areset_export,     //     pll_areset.export
		output wire        pll_locked_export,     //     pll_locked.export
		output wire        sdram_clk_clk,         //      sdram_clk.clk
		output wire [12:0] sdram_wire_addr,       //     sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,         //               .ba
		output wire        sdram_wire_cas_n,      //               .cas_n
		output wire        sdram_wire_cke,        //               .cke
		output wire        sdram_wire_cs_n,       //               .cs_n
		inout  wire [15:0] sdram_wire_dq,         //               .dq
		output wire [1:0]  sdram_wire_dqm,        //               .dqm
		output wire        sdram_wire_ras_n,      //               .ras_n
		output wire        sdram_wire_we_n,       //               .we_n
		input  wire [9:0]  sw_interface_export    //   sw_interface.export
	);

	wire          sdram_pll_c0_clk;                                                           // SDRAM_PLL:c0 -> [DEBUG:clk, DMA_IO:clock_clk, FLASH_MEM:clock, GPIO:clk_clk, IO_Modules:clk_clk, NIOS_II:clk, SDRAM:clk, SYS_ID:clock, irq_mapper:clk, mm_interconnect_0:SDRAM_PLL_c0_clk, rst_controller:clk, rst_controller_001:clk]
	wire          nios_ii_debug_reset_request_reset;                                          // NIOS_II:debug_reset_request -> [rst_controller:reset_in0, rst_controller_001:reset_in0, rst_controller_001:reset_in1, rst_controller_002:reset_in0]
	wire   [31:0] nios_ii_custom_instruction_master_multi_dataa;                              // NIOS_II:A_ci_multi_dataa -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_dataa
	wire          nios_ii_custom_instruction_master_multi_writerc;                            // NIOS_II:A_ci_multi_writerc -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_writerc
	wire   [31:0] nios_ii_custom_instruction_master_multi_result;                             // NIOS_II_custom_instruction_master_translator:ci_slave_multi_result -> NIOS_II:A_ci_multi_result
	wire          nios_ii_custom_instruction_master_clk;                                      // NIOS_II:A_ci_multi_clock -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_clk
	wire   [31:0] nios_ii_custom_instruction_master_multi_datab;                              // NIOS_II:A_ci_multi_datab -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_datab
	wire          nios_ii_custom_instruction_master_start;                                    // NIOS_II:A_ci_multi_start -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_start
	wire    [4:0] nios_ii_custom_instruction_master_multi_b;                                  // NIOS_II:A_ci_multi_b -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_b
	wire    [4:0] nios_ii_custom_instruction_master_multi_c;                                  // NIOS_II:A_ci_multi_c -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_c
	wire          nios_ii_custom_instruction_master_reset_req;                                // NIOS_II:A_ci_multi_reset_req -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_reset_req
	wire          nios_ii_custom_instruction_master_done;                                     // NIOS_II_custom_instruction_master_translator:ci_slave_multi_done -> NIOS_II:A_ci_multi_done
	wire    [4:0] nios_ii_custom_instruction_master_multi_a;                                  // NIOS_II:A_ci_multi_a -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_a
	wire          nios_ii_custom_instruction_master_clk_en;                                   // NIOS_II:A_ci_multi_clk_en -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_clken
	wire          nios_ii_custom_instruction_master_reset;                                    // NIOS_II:A_ci_multi_reset -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_reset
	wire          nios_ii_custom_instruction_master_multi_readrb;                             // NIOS_II:A_ci_multi_readrb -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_readrb
	wire          nios_ii_custom_instruction_master_multi_readra;                             // NIOS_II:A_ci_multi_readra -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_readra
	wire    [7:0] nios_ii_custom_instruction_master_multi_n;                                  // NIOS_II:A_ci_multi_n -> NIOS_II_custom_instruction_master_translator:ci_slave_multi_n
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_readra;        // NIOS_II_custom_instruction_master_translator:multi_ci_master_readra -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_readra
	wire    [4:0] nios_ii_custom_instruction_master_translator_multi_ci_master_a;             // NIOS_II_custom_instruction_master_translator:multi_ci_master_a -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_a
	wire    [4:0] nios_ii_custom_instruction_master_translator_multi_ci_master_b;             // NIOS_II_custom_instruction_master_translator:multi_ci_master_b -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_b
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_clk;           // NIOS_II_custom_instruction_master_translator:multi_ci_master_clk -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_clk
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_readrb;        // NIOS_II_custom_instruction_master_translator:multi_ci_master_readrb -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_readrb
	wire    [4:0] nios_ii_custom_instruction_master_translator_multi_ci_master_c;             // NIOS_II_custom_instruction_master_translator:multi_ci_master_c -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_c
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_start;         // NIOS_II_custom_instruction_master_translator:multi_ci_master_start -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_start
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_reset_req;     // NIOS_II_custom_instruction_master_translator:multi_ci_master_reset_req -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_reset_req
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_done;          // NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_done -> NIOS_II_custom_instruction_master_translator:multi_ci_master_done
	wire    [7:0] nios_ii_custom_instruction_master_translator_multi_ci_master_n;             // NIOS_II_custom_instruction_master_translator:multi_ci_master_n -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_n
	wire   [31:0] nios_ii_custom_instruction_master_translator_multi_ci_master_result;        // NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_result -> NIOS_II_custom_instruction_master_translator:multi_ci_master_result
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_clk_en;        // NIOS_II_custom_instruction_master_translator:multi_ci_master_clken -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_clken
	wire   [31:0] nios_ii_custom_instruction_master_translator_multi_ci_master_datab;         // NIOS_II_custom_instruction_master_translator:multi_ci_master_datab -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_datab
	wire   [31:0] nios_ii_custom_instruction_master_translator_multi_ci_master_dataa;         // NIOS_II_custom_instruction_master_translator:multi_ci_master_dataa -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_dataa
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_reset;         // NIOS_II_custom_instruction_master_translator:multi_ci_master_reset -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_reset
	wire          nios_ii_custom_instruction_master_translator_multi_ci_master_writerc;       // NIOS_II_custom_instruction_master_translator:multi_ci_master_writerc -> NIOS_II_custom_instruction_master_multi_xconnect:ci_slave_writerc
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_readra;         // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_readra -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_readra
	wire    [4:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_a;              // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_a -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_a
	wire    [4:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_b;              // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_b -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_b
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_readrb;         // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_readrb -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_readrb
	wire    [4:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_c;              // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_c -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_c
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_clk;            // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_clk -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_clk
	wire   [31:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_ipending;       // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_ipending -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_ipending
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_start;          // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_start -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_start
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_reset_req;      // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_reset_req -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_reset_req
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_done;           // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_done -> NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_done
	wire    [7:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_n;              // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_n -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_n
	wire   [31:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_result;         // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_result -> NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_result
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_estatus;        // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_estatus -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_estatus
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_clk_en;         // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_clken -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_clken
	wire   [31:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_datab;          // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_datab -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_datab
	wire   [31:0] nios_ii_custom_instruction_master_multi_xconnect_ci_master0_dataa;          // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_dataa -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_dataa
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_reset;          // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_reset -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_reset
	wire          nios_ii_custom_instruction_master_multi_xconnect_ci_master0_writerc;        // NIOS_II_custom_instruction_master_multi_xconnect:ci_master0_writerc -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_slave_writerc
	wire   [31:0] nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_result; // FPU:result -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_result
	wire          nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_clk;    // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_clk -> FPU:clk
	wire          nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_clk_en; // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_clken -> FPU:clk_en
	wire   [31:0] nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_datab;  // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_datab -> FPU:datab
	wire   [31:0] nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_dataa;  // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_dataa -> FPU:dataa
	wire          nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_start;  // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_start -> FPU:start
	wire          nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_reset;  // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_reset -> FPU:reset
	wire          nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_done;   // FPU:done -> NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_done
	wire    [1:0] nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_n;      // NIOS_II_custom_instruction_master_multi_slave_translator0:ci_master_n -> FPU:n
	wire   [31:0] nios_ii_data_master_readdata;                                               // mm_interconnect_0:NIOS_II_data_master_readdata -> NIOS_II:d_readdata
	wire          nios_ii_data_master_waitrequest;                                            // mm_interconnect_0:NIOS_II_data_master_waitrequest -> NIOS_II:d_waitrequest
	wire          nios_ii_data_master_debugaccess;                                            // NIOS_II:debug_mem_slave_debugaccess_to_roms -> mm_interconnect_0:NIOS_II_data_master_debugaccess
	wire   [26:0] nios_ii_data_master_address;                                                // NIOS_II:d_address -> mm_interconnect_0:NIOS_II_data_master_address
	wire    [3:0] nios_ii_data_master_byteenable;                                             // NIOS_II:d_byteenable -> mm_interconnect_0:NIOS_II_data_master_byteenable
	wire          nios_ii_data_master_read;                                                   // NIOS_II:d_read -> mm_interconnect_0:NIOS_II_data_master_read
	wire          nios_ii_data_master_readdatavalid;                                          // mm_interconnect_0:NIOS_II_data_master_readdatavalid -> NIOS_II:d_readdatavalid
	wire          nios_ii_data_master_write;                                                  // NIOS_II:d_write -> mm_interconnect_0:NIOS_II_data_master_write
	wire   [31:0] nios_ii_data_master_writedata;                                              // NIOS_II:d_writedata -> mm_interconnect_0:NIOS_II_data_master_writedata
	wire   [31:0] nios_ii_instruction_master_readdata;                                        // mm_interconnect_0:NIOS_II_instruction_master_readdata -> NIOS_II:i_readdata
	wire          nios_ii_instruction_master_waitrequest;                                     // mm_interconnect_0:NIOS_II_instruction_master_waitrequest -> NIOS_II:i_waitrequest
	wire   [26:0] nios_ii_instruction_master_address;                                         // NIOS_II:i_address -> mm_interconnect_0:NIOS_II_instruction_master_address
	wire          nios_ii_instruction_master_read;                                            // NIOS_II:i_read -> mm_interconnect_0:NIOS_II_instruction_master_read
	wire          nios_ii_instruction_master_readdatavalid;                                   // mm_interconnect_0:NIOS_II_instruction_master_readdatavalid -> NIOS_II:i_readdatavalid
	wire   [31:0] dma_io_mm_read_readdata;                                                    // mm_interconnect_0:DMA_IO_mm_read_readdata -> DMA_IO:mm_read_readdata
	wire          dma_io_mm_read_waitrequest;                                                 // mm_interconnect_0:DMA_IO_mm_read_waitrequest -> DMA_IO:mm_read_waitrequest
	wire   [26:0] dma_io_mm_read_address;                                                     // DMA_IO:mm_read_address -> mm_interconnect_0:DMA_IO_mm_read_address
	wire          dma_io_mm_read_read;                                                        // DMA_IO:mm_read_read -> mm_interconnect_0:DMA_IO_mm_read_read
	wire    [3:0] dma_io_mm_read_byteenable;                                                  // DMA_IO:mm_read_byteenable -> mm_interconnect_0:DMA_IO_mm_read_byteenable
	wire          dma_io_mm_read_readdatavalid;                                               // mm_interconnect_0:DMA_IO_mm_read_readdatavalid -> DMA_IO:mm_read_readdatavalid
	wire          gpio_mm_write_waitrequest;                                                  // mm_interconnect_0:GPIO_mm_write_waitrequest -> GPIO:mm_write_waitrequest
	wire   [25:0] gpio_mm_write_address;                                                      // GPIO:mm_write_address -> mm_interconnect_0:GPIO_mm_write_address
	wire    [7:0] gpio_mm_write_byteenable;                                                   // GPIO:mm_write_byteenable -> mm_interconnect_0:GPIO_mm_write_byteenable
	wire          gpio_mm_write_write;                                                        // GPIO:mm_write_write -> mm_interconnect_0:GPIO_mm_write_write
	wire   [63:0] gpio_mm_write_writedata;                                                    // GPIO:mm_write_writedata -> mm_interconnect_0:GPIO_mm_write_writedata
	wire          dma_io_mm_write_waitrequest;                                                // mm_interconnect_0:DMA_IO_mm_write_waitrequest -> DMA_IO:mm_write_waitrequest
	wire   [26:0] dma_io_mm_write_address;                                                    // DMA_IO:mm_write_address -> mm_interconnect_0:DMA_IO_mm_write_address
	wire    [3:0] dma_io_mm_write_byteenable;                                                 // DMA_IO:mm_write_byteenable -> mm_interconnect_0:DMA_IO_mm_write_byteenable
	wire          dma_io_mm_write_write;                                                      // DMA_IO:mm_write_write -> mm_interconnect_0:DMA_IO_mm_write_write
	wire   [31:0] dma_io_mm_write_writedata;                                                  // DMA_IO:mm_write_writedata -> mm_interconnect_0:DMA_IO_mm_write_writedata
	wire          mm_interconnect_0_debug_avalon_jtag_slave_chipselect;                       // mm_interconnect_0:DEBUG_avalon_jtag_slave_chipselect -> DEBUG:av_chipselect
	wire   [31:0] mm_interconnect_0_debug_avalon_jtag_slave_readdata;                         // DEBUG:av_readdata -> mm_interconnect_0:DEBUG_avalon_jtag_slave_readdata
	wire          mm_interconnect_0_debug_avalon_jtag_slave_waitrequest;                      // DEBUG:av_waitrequest -> mm_interconnect_0:DEBUG_avalon_jtag_slave_waitrequest
	wire    [0:0] mm_interconnect_0_debug_avalon_jtag_slave_address;                          // mm_interconnect_0:DEBUG_avalon_jtag_slave_address -> DEBUG:av_address
	wire          mm_interconnect_0_debug_avalon_jtag_slave_read;                             // mm_interconnect_0:DEBUG_avalon_jtag_slave_read -> DEBUG:av_read_n
	wire          mm_interconnect_0_debug_avalon_jtag_slave_write;                            // mm_interconnect_0:DEBUG_avalon_jtag_slave_write -> DEBUG:av_write_n
	wire   [31:0] mm_interconnect_0_debug_avalon_jtag_slave_writedata;                        // mm_interconnect_0:DEBUG_avalon_jtag_slave_writedata -> DEBUG:av_writedata
	wire   [31:0] mm_interconnect_0_sys_id_control_slave_readdata;                            // SYS_ID:readdata -> mm_interconnect_0:SYS_ID_control_slave_readdata
	wire    [0:0] mm_interconnect_0_sys_id_control_slave_address;                             // mm_interconnect_0:SYS_ID_control_slave_address -> SYS_ID:address
	wire   [31:0] mm_interconnect_0_flash_mem_csr_readdata;                                   // FLASH_MEM:avmm_csr_readdata -> mm_interconnect_0:FLASH_MEM_csr_readdata
	wire    [0:0] mm_interconnect_0_flash_mem_csr_address;                                    // mm_interconnect_0:FLASH_MEM_csr_address -> FLASH_MEM:avmm_csr_addr
	wire          mm_interconnect_0_flash_mem_csr_read;                                       // mm_interconnect_0:FLASH_MEM_csr_read -> FLASH_MEM:avmm_csr_read
	wire          mm_interconnect_0_flash_mem_csr_write;                                      // mm_interconnect_0:FLASH_MEM_csr_write -> FLASH_MEM:avmm_csr_write
	wire   [31:0] mm_interconnect_0_flash_mem_csr_writedata;                                  // mm_interconnect_0:FLASH_MEM_csr_writedata -> FLASH_MEM:avmm_csr_writedata
	wire   [31:0] mm_interconnect_0_dma_io_csr_readdata;                                      // DMA_IO:csr_readdata -> mm_interconnect_0:DMA_IO_csr_readdata
	wire    [2:0] mm_interconnect_0_dma_io_csr_address;                                       // mm_interconnect_0:DMA_IO_csr_address -> DMA_IO:csr_address
	wire          mm_interconnect_0_dma_io_csr_read;                                          // mm_interconnect_0:DMA_IO_csr_read -> DMA_IO:csr_read
	wire    [3:0] mm_interconnect_0_dma_io_csr_byteenable;                                    // mm_interconnect_0:DMA_IO_csr_byteenable -> DMA_IO:csr_byteenable
	wire          mm_interconnect_0_dma_io_csr_write;                                         // mm_interconnect_0:DMA_IO_csr_write -> DMA_IO:csr_write
	wire   [31:0] mm_interconnect_0_dma_io_csr_writedata;                                     // mm_interconnect_0:DMA_IO_csr_writedata -> DMA_IO:csr_writedata
	wire   [31:0] mm_interconnect_0_flash_mem_data_readdata;                                  // FLASH_MEM:avmm_data_readdata -> mm_interconnect_0:FLASH_MEM_data_readdata
	wire          mm_interconnect_0_flash_mem_data_waitrequest;                               // FLASH_MEM:avmm_data_waitrequest -> mm_interconnect_0:FLASH_MEM_data_waitrequest
	wire   [18:0] mm_interconnect_0_flash_mem_data_address;                                   // mm_interconnect_0:FLASH_MEM_data_address -> FLASH_MEM:avmm_data_addr
	wire          mm_interconnect_0_flash_mem_data_read;                                      // mm_interconnect_0:FLASH_MEM_data_read -> FLASH_MEM:avmm_data_read
	wire          mm_interconnect_0_flash_mem_data_readdatavalid;                             // FLASH_MEM:avmm_data_readdatavalid -> mm_interconnect_0:FLASH_MEM_data_readdatavalid
	wire          mm_interconnect_0_flash_mem_data_write;                                     // mm_interconnect_0:FLASH_MEM_data_write -> FLASH_MEM:avmm_data_write
	wire   [31:0] mm_interconnect_0_flash_mem_data_writedata;                                 // mm_interconnect_0:FLASH_MEM_data_writedata -> FLASH_MEM:avmm_data_writedata
	wire    [3:0] mm_interconnect_0_flash_mem_data_burstcount;                                // mm_interconnect_0:FLASH_MEM_data_burstcount -> FLASH_MEM:avmm_data_burstcount
	wire   [31:0] mm_interconnect_0_nios_ii_debug_mem_slave_readdata;                         // NIOS_II:debug_mem_slave_readdata -> mm_interconnect_0:NIOS_II_debug_mem_slave_readdata
	wire          mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest;                      // NIOS_II:debug_mem_slave_waitrequest -> mm_interconnect_0:NIOS_II_debug_mem_slave_waitrequest
	wire          mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess;                      // mm_interconnect_0:NIOS_II_debug_mem_slave_debugaccess -> NIOS_II:debug_mem_slave_debugaccess
	wire    [8:0] mm_interconnect_0_nios_ii_debug_mem_slave_address;                          // mm_interconnect_0:NIOS_II_debug_mem_slave_address -> NIOS_II:debug_mem_slave_address
	wire          mm_interconnect_0_nios_ii_debug_mem_slave_read;                             // mm_interconnect_0:NIOS_II_debug_mem_slave_read -> NIOS_II:debug_mem_slave_read
	wire    [3:0] mm_interconnect_0_nios_ii_debug_mem_slave_byteenable;                       // mm_interconnect_0:NIOS_II_debug_mem_slave_byteenable -> NIOS_II:debug_mem_slave_byteenable
	wire          mm_interconnect_0_nios_ii_debug_mem_slave_write;                            // mm_interconnect_0:NIOS_II_debug_mem_slave_write -> NIOS_II:debug_mem_slave_write
	wire   [31:0] mm_interconnect_0_nios_ii_debug_mem_slave_writedata;                        // mm_interconnect_0:NIOS_II_debug_mem_slave_writedata -> NIOS_II:debug_mem_slave_writedata
	wire          mm_interconnect_0_dma_io_descriptor_slave_waitrequest;                      // DMA_IO:descriptor_slave_waitrequest -> mm_interconnect_0:DMA_IO_descriptor_slave_waitrequest
	wire   [15:0] mm_interconnect_0_dma_io_descriptor_slave_byteenable;                       // mm_interconnect_0:DMA_IO_descriptor_slave_byteenable -> DMA_IO:descriptor_slave_byteenable
	wire          mm_interconnect_0_dma_io_descriptor_slave_write;                            // mm_interconnect_0:DMA_IO_descriptor_slave_write -> DMA_IO:descriptor_slave_write
	wire  [127:0] mm_interconnect_0_dma_io_descriptor_slave_writedata;                        // mm_interconnect_0:DMA_IO_descriptor_slave_writedata -> DMA_IO:descriptor_slave_writedata
	wire   [31:0] mm_interconnect_0_gpio_s0_readdata;                                         // GPIO:s0_readdata -> mm_interconnect_0:GPIO_s0_readdata
	wire          mm_interconnect_0_gpio_s0_waitrequest;                                      // GPIO:s0_waitrequest -> mm_interconnect_0:GPIO_s0_waitrequest
	wire          mm_interconnect_0_gpio_s0_debugaccess;                                      // mm_interconnect_0:GPIO_s0_debugaccess -> GPIO:s0_debugaccess
	wire    [9:0] mm_interconnect_0_gpio_s0_address;                                          // mm_interconnect_0:GPIO_s0_address -> GPIO:s0_address
	wire          mm_interconnect_0_gpio_s0_read;                                             // mm_interconnect_0:GPIO_s0_read -> GPIO:s0_read
	wire    [3:0] mm_interconnect_0_gpio_s0_byteenable;                                       // mm_interconnect_0:GPIO_s0_byteenable -> GPIO:s0_byteenable
	wire          mm_interconnect_0_gpio_s0_readdatavalid;                                    // GPIO:s0_readdatavalid -> mm_interconnect_0:GPIO_s0_readdatavalid
	wire          mm_interconnect_0_gpio_s0_write;                                            // mm_interconnect_0:GPIO_s0_write -> GPIO:s0_write
	wire   [31:0] mm_interconnect_0_gpio_s0_writedata;                                        // mm_interconnect_0:GPIO_s0_writedata -> GPIO:s0_writedata
	wire    [0:0] mm_interconnect_0_gpio_s0_burstcount;                                       // mm_interconnect_0:GPIO_s0_burstcount -> GPIO:s0_burstcount
	wire   [31:0] mm_interconnect_0_io_modules_s0_readdata;                                   // IO_Modules:s0_readdata -> mm_interconnect_0:IO_Modules_s0_readdata
	wire          mm_interconnect_0_io_modules_s0_waitrequest;                                // IO_Modules:s0_waitrequest -> mm_interconnect_0:IO_Modules_s0_waitrequest
	wire          mm_interconnect_0_io_modules_s0_debugaccess;                                // mm_interconnect_0:IO_Modules_s0_debugaccess -> IO_Modules:s0_debugaccess
	wire    [9:0] mm_interconnect_0_io_modules_s0_address;                                    // mm_interconnect_0:IO_Modules_s0_address -> IO_Modules:s0_address
	wire          mm_interconnect_0_io_modules_s0_read;                                       // mm_interconnect_0:IO_Modules_s0_read -> IO_Modules:s0_read
	wire    [3:0] mm_interconnect_0_io_modules_s0_byteenable;                                 // mm_interconnect_0:IO_Modules_s0_byteenable -> IO_Modules:s0_byteenable
	wire          mm_interconnect_0_io_modules_s0_readdatavalid;                              // IO_Modules:s0_readdatavalid -> mm_interconnect_0:IO_Modules_s0_readdatavalid
	wire          mm_interconnect_0_io_modules_s0_write;                                      // mm_interconnect_0:IO_Modules_s0_write -> IO_Modules:s0_write
	wire   [31:0] mm_interconnect_0_io_modules_s0_writedata;                                  // mm_interconnect_0:IO_Modules_s0_writedata -> IO_Modules:s0_writedata
	wire    [0:0] mm_interconnect_0_io_modules_s0_burstcount;                                 // mm_interconnect_0:IO_Modules_s0_burstcount -> IO_Modules:s0_burstcount
	wire          mm_interconnect_0_sdram_s1_chipselect;                                      // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire   [15:0] mm_interconnect_0_sdram_s1_readdata;                                        // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire          mm_interconnect_0_sdram_s1_waitrequest;                                     // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire   [24:0] mm_interconnect_0_sdram_s1_address;                                         // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire          mm_interconnect_0_sdram_s1_read;                                            // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire    [1:0] mm_interconnect_0_sdram_s1_byteenable;                                      // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire          mm_interconnect_0_sdram_s1_readdatavalid;                                   // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire          mm_interconnect_0_sdram_s1_write;                                           // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire   [15:0] mm_interconnect_0_sdram_s1_writedata;                                       // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire          irq_mapper_receiver0_irq;                                                   // GPIO:csr_irq_irq -> irq_mapper:receiver0_irq
	wire          irq_mapper_receiver1_irq;                                                   // DMA_IO:csr_irq_irq -> irq_mapper:receiver1_irq
	wire          irq_mapper_receiver2_irq;                                                   // DEBUG:av_irq -> irq_mapper:receiver2_irq
	wire   [31:0] nios_ii_irq_irq;                                                            // irq_mapper:sender_irq -> NIOS_II:irq
	wire          rst_controller_reset_out_reset;                                             // rst_controller:reset_out -> [DEBUG:rst_n, DMA_IO:reset_n_reset_n, FLASH_MEM:reset_n, GPIO:reset_reset, IO_Modules:reset_reset, SDRAM:reset_n, SYS_ID:reset_n, mm_interconnect_0:DMA_IO_reset_n_reset_bridge_in_reset_reset]
	wire          rst_controller_001_reset_out_reset;                                         // rst_controller_001:reset_out -> [NIOS_II:reset_n, irq_mapper:reset, mm_interconnect_0:NIOS_II_reset_reset_bridge_in_reset_reset]
	wire          rst_controller_001_reset_out_reset_req;                                     // rst_controller_001:reset_req -> [NIOS_II:reset_req, rst_translator:reset_req_in]
	wire          rst_controller_002_reset_out_reset;                                         // rst_controller_002:reset_out -> SDRAM_PLL:reset

	signal_analyzer_DEBUG debug (
		.clk            (sdram_pll_c0_clk),                                      //               clk.clk
		.rst_n          (~rst_controller_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_debug_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_debug_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_debug_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_mapper_receiver2_irq)                               //               irq.irq
	);

	signal_analyzer_DMA_IO dma_io (
		.mm_read_address              (dma_io_mm_read_address),                                //          mm_read.address
		.mm_read_read                 (dma_io_mm_read_read),                                   //                 .read
		.mm_read_byteenable           (dma_io_mm_read_byteenable),                             //                 .byteenable
		.mm_read_readdata             (dma_io_mm_read_readdata),                               //                 .readdata
		.mm_read_waitrequest          (dma_io_mm_read_waitrequest),                            //                 .waitrequest
		.mm_read_readdatavalid        (dma_io_mm_read_readdatavalid),                          //                 .readdatavalid
		.mm_write_address             (dma_io_mm_write_address),                               //         mm_write.address
		.mm_write_write               (dma_io_mm_write_write),                                 //                 .write
		.mm_write_byteenable          (dma_io_mm_write_byteenable),                            //                 .byteenable
		.mm_write_writedata           (dma_io_mm_write_writedata),                             //                 .writedata
		.mm_write_waitrequest         (dma_io_mm_write_waitrequest),                           //                 .waitrequest
		.clock_clk                    (sdram_pll_c0_clk),                                      //            clock.clk
		.reset_n_reset_n              (~rst_controller_reset_out_reset),                       //          reset_n.reset_n
		.csr_writedata                (mm_interconnect_0_dma_io_csr_writedata),                //              csr.writedata
		.csr_write                    (mm_interconnect_0_dma_io_csr_write),                    //                 .write
		.csr_byteenable               (mm_interconnect_0_dma_io_csr_byteenable),               //                 .byteenable
		.csr_readdata                 (mm_interconnect_0_dma_io_csr_readdata),                 //                 .readdata
		.csr_read                     (mm_interconnect_0_dma_io_csr_read),                     //                 .read
		.csr_address                  (mm_interconnect_0_dma_io_csr_address),                  //                 .address
		.descriptor_slave_write       (mm_interconnect_0_dma_io_descriptor_slave_write),       // descriptor_slave.write
		.descriptor_slave_waitrequest (mm_interconnect_0_dma_io_descriptor_slave_waitrequest), //                 .waitrequest
		.descriptor_slave_writedata   (mm_interconnect_0_dma_io_descriptor_slave_writedata),   //                 .writedata
		.descriptor_slave_byteenable  (mm_interconnect_0_dma_io_descriptor_slave_byteenable),  //                 .byteenable
		.csr_irq_irq                  (irq_mapper_receiver1_irq)                               //          csr_irq.irq
	);

	altera_onchip_flash #(
		.INIT_FILENAME                       (""),
		.INIT_FILENAME_SIM                   (""),
		.DEVICE_FAMILY                       ("MAX 10"),
		.PART_NAME                           ("10M50DAF484C7G"),
		.DEVICE_ID                           ("50"),
		.SECTOR1_START_ADDR                  (0),
		.SECTOR1_END_ADDR                    (8191),
		.SECTOR2_START_ADDR                  (8192),
		.SECTOR2_END_ADDR                    (16383),
		.SECTOR3_START_ADDR                  (16384),
		.SECTOR3_END_ADDR                    (114687),
		.SECTOR4_START_ADDR                  (114688),
		.SECTOR4_END_ADDR                    (188415),
		.SECTOR5_START_ADDR                  (188416),
		.SECTOR5_END_ADDR                    (360447),
		.MIN_VALID_ADDR                      (0),
		.MAX_VALID_ADDR                      (360447),
		.MIN_UFM_VALID_ADDR                  (0),
		.MAX_UFM_VALID_ADDR                  (16383),
		.SECTOR1_MAP                         (1),
		.SECTOR2_MAP                         (2),
		.SECTOR3_MAP                         (3),
		.SECTOR4_MAP                         (4),
		.SECTOR5_MAP                         (5),
		.ADDR_RANGE1_END_ADDR                (360447),
		.ADDR_RANGE2_END_ADDR                (360447),
		.ADDR_RANGE1_OFFSET                  (2048),
		.ADDR_RANGE2_OFFSET                  (0),
		.ADDR_RANGE3_OFFSET                  (0),
		.AVMM_DATA_ADDR_WIDTH                (19),
		.AVMM_DATA_DATA_WIDTH                (32),
		.AVMM_DATA_BURSTCOUNT_WIDTH          (4),
		.SECTOR_READ_PROTECTION_MODE         (0),
		.FLASH_SEQ_READ_DATA_COUNT           (4),
		.FLASH_ADDR_ALIGNMENT_BITS           (2),
		.FLASH_READ_CYCLE_MAX_INDEX          (5),
		.FLASH_RESET_CYCLE_MAX_INDEX         (12),
		.FLASH_BUSY_TIMEOUT_CYCLE_MAX_INDEX  (60),
		.FLASH_ERASE_TIMEOUT_CYCLE_MAX_INDEX (17500000),
		.FLASH_WRITE_TIMEOUT_CYCLE_MAX_INDEX (15250),
		.PARALLEL_MODE                       (1),
		.READ_AND_WRITE_MODE                 (1),
		.WRAPPING_BURST_MODE                 (0),
		.IS_DUAL_BOOT                        ("False"),
		.IS_ERAM_SKIP                        ("False"),
		.IS_COMPRESSED_IMAGE                 ("False")
	) flash_mem (
		.clock                   (sdram_pll_c0_clk),                               //    clk.clk
		.reset_n                 (~rst_controller_reset_out_reset),                // nreset.reset_n
		.avmm_data_addr          (mm_interconnect_0_flash_mem_data_address),       //   data.address
		.avmm_data_read          (mm_interconnect_0_flash_mem_data_read),          //       .read
		.avmm_data_writedata     (mm_interconnect_0_flash_mem_data_writedata),     //       .writedata
		.avmm_data_write         (mm_interconnect_0_flash_mem_data_write),         //       .write
		.avmm_data_readdata      (mm_interconnect_0_flash_mem_data_readdata),      //       .readdata
		.avmm_data_waitrequest   (mm_interconnect_0_flash_mem_data_waitrequest),   //       .waitrequest
		.avmm_data_readdatavalid (mm_interconnect_0_flash_mem_data_readdatavalid), //       .readdatavalid
		.avmm_data_burstcount    (mm_interconnect_0_flash_mem_data_burstcount),    //       .burstcount
		.avmm_csr_addr           (mm_interconnect_0_flash_mem_csr_address),        //    csr.address
		.avmm_csr_read           (mm_interconnect_0_flash_mem_csr_read),           //       .read
		.avmm_csr_writedata      (mm_interconnect_0_flash_mem_csr_writedata),      //       .writedata
		.avmm_csr_write          (mm_interconnect_0_flash_mem_csr_write),          //       .write
		.avmm_csr_readdata       (mm_interconnect_0_flash_mem_csr_readdata)        //       .readdata
	);

	fpoint_wrapper #(
		.useDivider (1)
	) fpu (
		.clk    (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_clk),    // s1.clk
		.clk_en (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_clk_en), //   .clk_en
		.dataa  (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_dataa),  //   .dataa
		.datab  (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_datab),  //   .datab
		.n      (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_n),      //   .n
		.reset  (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_reset),  //   .reset
		.start  (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_start),  //   .start
		.done   (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_done),   //   .done
		.result (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_result)  //   .result
	);

	signal_analyzer_GPIO gpio (
		.clk_clk               (sdram_pll_c0_clk),                        //            clk.clk
		.csr_irq_irq           (irq_mapper_receiver0_irq),                //        csr_irq.irq
		.gpio_interface_export (gpio_interface_export),                   // gpio_interface.export
		.mm_write_address      (gpio_mm_write_address),                   //       mm_write.address
		.mm_write_write        (gpio_mm_write_write),                     //               .write
		.mm_write_byteenable   (gpio_mm_write_byteenable),                //               .byteenable
		.mm_write_writedata    (gpio_mm_write_writedata),                 //               .writedata
		.mm_write_waitrequest  (gpio_mm_write_waitrequest),               //               .waitrequest
		.reset_reset           (rst_controller_reset_out_reset),          //          reset.reset
		.s0_waitrequest        (mm_interconnect_0_gpio_s0_waitrequest),   //             s0.waitrequest
		.s0_readdata           (mm_interconnect_0_gpio_s0_readdata),      //               .readdata
		.s0_readdatavalid      (mm_interconnect_0_gpio_s0_readdatavalid), //               .readdatavalid
		.s0_burstcount         (mm_interconnect_0_gpio_s0_burstcount),    //               .burstcount
		.s0_writedata          (mm_interconnect_0_gpio_s0_writedata),     //               .writedata
		.s0_address            (mm_interconnect_0_gpio_s0_address),       //               .address
		.s0_write              (mm_interconnect_0_gpio_s0_write),         //               .write
		.s0_read               (mm_interconnect_0_gpio_s0_read),          //               .read
		.s0_byteenable         (mm_interconnect_0_gpio_s0_byteenable),    //               .byteenable
		.s0_debugaccess        (mm_interconnect_0_gpio_s0_debugaccess)    //               .debugaccess
	);

	signal_analyzer_IO_Modules io_modules (
		.clk_clk              (sdram_pll_c0_clk),                              //           clk.clk
		.hex_interface_hex_0  (hex_interface_hex_0),                           // hex_interface.hex_0
		.hex_interface_hex_1  (hex_interface_hex_1),                           //              .hex_1
		.hex_interface_hex_2  (hex_interface_hex_2),                           //              .hex_2
		.hex_interface_hex_3  (hex_interface_hex_3),                           //              .hex_3
		.hex_interface_hex_4  (hex_interface_hex_4),                           //              .hex_4
		.hex_interface_hex_5  (hex_interface_hex_5),                           //              .hex_5
		.key_interface_export (key_interface_export),                          // key_interface.export
		.reset_reset          (rst_controller_reset_out_reset),                //         reset.reset
		.s0_waitrequest       (mm_interconnect_0_io_modules_s0_waitrequest),   //            s0.waitrequest
		.s0_readdata          (mm_interconnect_0_io_modules_s0_readdata),      //              .readdata
		.s0_readdatavalid     (mm_interconnect_0_io_modules_s0_readdatavalid), //              .readdatavalid
		.s0_burstcount        (mm_interconnect_0_io_modules_s0_burstcount),    //              .burstcount
		.s0_writedata         (mm_interconnect_0_io_modules_s0_writedata),     //              .writedata
		.s0_address           (mm_interconnect_0_io_modules_s0_address),       //              .address
		.s0_write             (mm_interconnect_0_io_modules_s0_write),         //              .write
		.s0_read              (mm_interconnect_0_io_modules_s0_read),          //              .read
		.s0_byteenable        (mm_interconnect_0_io_modules_s0_byteenable),    //              .byteenable
		.s0_debugaccess       (mm_interconnect_0_io_modules_s0_debugaccess),   //              .debugaccess
		.sw_interface_export  (sw_interface_export)                            //  sw_interface.export
	);

	signal_analyzer_NIOS_II nios_ii (
		.clk                                 (sdram_pll_c0_clk),                                      //                       clk.clk
		.reset_n                             (~rst_controller_001_reset_out_reset),                   //                     reset.reset_n
		.reset_req                           (rst_controller_001_reset_out_reset_req),                //                          .reset_req
		.d_address                           (nios_ii_data_master_address),                           //               data_master.address
		.d_byteenable                        (nios_ii_data_master_byteenable),                        //                          .byteenable
		.d_read                              (nios_ii_data_master_read),                              //                          .read
		.d_readdata                          (nios_ii_data_master_readdata),                          //                          .readdata
		.d_waitrequest                       (nios_ii_data_master_waitrequest),                       //                          .waitrequest
		.d_write                             (nios_ii_data_master_write),                             //                          .write
		.d_writedata                         (nios_ii_data_master_writedata),                         //                          .writedata
		.d_readdatavalid                     (nios_ii_data_master_readdatavalid),                     //                          .readdatavalid
		.debug_mem_slave_debugaccess_to_roms (nios_ii_data_master_debugaccess),                       //                          .debugaccess
		.i_address                           (nios_ii_instruction_master_address),                    //        instruction_master.address
		.i_read                              (nios_ii_instruction_master_read),                       //                          .read
		.i_readdata                          (nios_ii_instruction_master_readdata),                   //                          .readdata
		.i_waitrequest                       (nios_ii_instruction_master_waitrequest),                //                          .waitrequest
		.i_readdatavalid                     (nios_ii_instruction_master_readdatavalid),              //                          .readdatavalid
		.irq                                 (nios_ii_irq_irq),                                       //                       irq.irq
		.debug_reset_request                 (nios_ii_debug_reset_request_reset),                     //       debug_reset_request.reset
		.debug_mem_slave_address             (mm_interconnect_0_nios_ii_debug_mem_slave_address),     //           debug_mem_slave.address
		.debug_mem_slave_byteenable          (mm_interconnect_0_nios_ii_debug_mem_slave_byteenable),  //                          .byteenable
		.debug_mem_slave_debugaccess         (mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess), //                          .debugaccess
		.debug_mem_slave_read                (mm_interconnect_0_nios_ii_debug_mem_slave_read),        //                          .read
		.debug_mem_slave_readdata            (mm_interconnect_0_nios_ii_debug_mem_slave_readdata),    //                          .readdata
		.debug_mem_slave_waitrequest         (mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest), //                          .waitrequest
		.debug_mem_slave_write               (mm_interconnect_0_nios_ii_debug_mem_slave_write),       //                          .write
		.debug_mem_slave_writedata           (mm_interconnect_0_nios_ii_debug_mem_slave_writedata),   //                          .writedata
		.A_ci_multi_done                     (nios_ii_custom_instruction_master_done),                // custom_instruction_master.done
		.A_ci_multi_result                   (nios_ii_custom_instruction_master_multi_result),        //                          .multi_result
		.A_ci_multi_a                        (nios_ii_custom_instruction_master_multi_a),             //                          .multi_a
		.A_ci_multi_b                        (nios_ii_custom_instruction_master_multi_b),             //                          .multi_b
		.A_ci_multi_c                        (nios_ii_custom_instruction_master_multi_c),             //                          .multi_c
		.A_ci_multi_clk_en                   (nios_ii_custom_instruction_master_clk_en),              //                          .clk_en
		.A_ci_multi_clock                    (nios_ii_custom_instruction_master_clk),                 //                          .clk
		.A_ci_multi_reset                    (nios_ii_custom_instruction_master_reset),               //                          .reset
		.A_ci_multi_reset_req                (nios_ii_custom_instruction_master_reset_req),           //                          .reset_req
		.A_ci_multi_dataa                    (nios_ii_custom_instruction_master_multi_dataa),         //                          .multi_dataa
		.A_ci_multi_datab                    (nios_ii_custom_instruction_master_multi_datab),         //                          .multi_datab
		.A_ci_multi_n                        (nios_ii_custom_instruction_master_multi_n),             //                          .multi_n
		.A_ci_multi_readra                   (nios_ii_custom_instruction_master_multi_readra),        //                          .multi_readra
		.A_ci_multi_readrb                   (nios_ii_custom_instruction_master_multi_readrb),        //                          .multi_readrb
		.A_ci_multi_start                    (nios_ii_custom_instruction_master_start),               //                          .start
		.A_ci_multi_writerc                  (nios_ii_custom_instruction_master_multi_writerc)        //                          .multi_writerc
	);

	signal_analyzer_SDRAM sdram (
		.clk            (sdram_pll_c0_clk),                         //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	signal_analyzer_SDRAM_PLL sdram_pll (
		.clk                (clk_clk),                            //       inclk_interface.clk
		.reset              (rst_controller_002_reset_out_reset), // inclk_interface_reset.reset
		.read               (),                                   //             pll_slave.read
		.write              (),                                   //                      .write
		.address            (),                                   //                      .address
		.readdata           (),                                   //                      .readdata
		.writedata          (),                                   //                      .writedata
		.c0                 (sdram_pll_c0_clk),                   //                    c0.clk
		.c1                 (sdram_clk_clk),                      //                    c1.clk
		.areset             (pll_areset_export),                  //        areset_conduit.export
		.locked             (pll_locked_export),                  //        locked_conduit.export
		.scandone           (),                                   //           (terminated)
		.scandataout        (),                                   //           (terminated)
		.c2                 (),                                   //           (terminated)
		.c3                 (),                                   //           (terminated)
		.c4                 (),                                   //           (terminated)
		.phasedone          (),                                   //           (terminated)
		.phasecounterselect (3'b000),                             //           (terminated)
		.phaseupdown        (1'b0),                               //           (terminated)
		.phasestep          (1'b0),                               //           (terminated)
		.scanclk            (1'b0),                               //           (terminated)
		.scanclkena         (1'b0),                               //           (terminated)
		.scandata           (1'b0),                               //           (terminated)
		.configupdate       (1'b0)                                //           (terminated)
	);

	signal_analyzer_SYS_ID sys_id (
		.clock    (sdram_pll_c0_clk),                                //           clk.clk
		.reset_n  (~rst_controller_reset_out_reset),                 //         reset.reset_n
		.readdata (mm_interconnect_0_sys_id_control_slave_readdata), // control_slave.readdata
		.address  (mm_interconnect_0_sys_id_control_slave_address)   //              .address
	);

	altera_customins_master_translator #(
		.SHARED_COMB_AND_MULTI (0)
	) nios_ii_custom_instruction_master_translator (
		.ci_slave_result           (),                                                                       //        ci_slave.result
		.ci_slave_multi_clk        (nios_ii_custom_instruction_master_clk),                                  //                .clk
		.ci_slave_multi_reset      (nios_ii_custom_instruction_master_reset),                                //                .reset
		.ci_slave_multi_clken      (nios_ii_custom_instruction_master_clk_en),                               //                .clk_en
		.ci_slave_multi_reset_req  (nios_ii_custom_instruction_master_reset_req),                            //                .reset_req
		.ci_slave_multi_start      (nios_ii_custom_instruction_master_start),                                //                .start
		.ci_slave_multi_done       (nios_ii_custom_instruction_master_done),                                 //                .done
		.ci_slave_multi_dataa      (nios_ii_custom_instruction_master_multi_dataa),                          //                .multi_dataa
		.ci_slave_multi_datab      (nios_ii_custom_instruction_master_multi_datab),                          //                .multi_datab
		.ci_slave_multi_result     (nios_ii_custom_instruction_master_multi_result),                         //                .multi_result
		.ci_slave_multi_n          (nios_ii_custom_instruction_master_multi_n),                              //                .multi_n
		.ci_slave_multi_readra     (nios_ii_custom_instruction_master_multi_readra),                         //                .multi_readra
		.ci_slave_multi_readrb     (nios_ii_custom_instruction_master_multi_readrb),                         //                .multi_readrb
		.ci_slave_multi_writerc    (nios_ii_custom_instruction_master_multi_writerc),                        //                .multi_writerc
		.ci_slave_multi_a          (nios_ii_custom_instruction_master_multi_a),                              //                .multi_a
		.ci_slave_multi_b          (nios_ii_custom_instruction_master_multi_b),                              //                .multi_b
		.ci_slave_multi_c          (nios_ii_custom_instruction_master_multi_c),                              //                .multi_c
		.comb_ci_master_result     (),                                                                       //  comb_ci_master.result
		.multi_ci_master_clk       (nios_ii_custom_instruction_master_translator_multi_ci_master_clk),       // multi_ci_master.clk
		.multi_ci_master_reset     (nios_ii_custom_instruction_master_translator_multi_ci_master_reset),     //                .reset
		.multi_ci_master_clken     (nios_ii_custom_instruction_master_translator_multi_ci_master_clk_en),    //                .clk_en
		.multi_ci_master_reset_req (nios_ii_custom_instruction_master_translator_multi_ci_master_reset_req), //                .reset_req
		.multi_ci_master_start     (nios_ii_custom_instruction_master_translator_multi_ci_master_start),     //                .start
		.multi_ci_master_done      (nios_ii_custom_instruction_master_translator_multi_ci_master_done),      //                .done
		.multi_ci_master_dataa     (nios_ii_custom_instruction_master_translator_multi_ci_master_dataa),     //                .dataa
		.multi_ci_master_datab     (nios_ii_custom_instruction_master_translator_multi_ci_master_datab),     //                .datab
		.multi_ci_master_result    (nios_ii_custom_instruction_master_translator_multi_ci_master_result),    //                .result
		.multi_ci_master_n         (nios_ii_custom_instruction_master_translator_multi_ci_master_n),         //                .n
		.multi_ci_master_readra    (nios_ii_custom_instruction_master_translator_multi_ci_master_readra),    //                .readra
		.multi_ci_master_readrb    (nios_ii_custom_instruction_master_translator_multi_ci_master_readrb),    //                .readrb
		.multi_ci_master_writerc   (nios_ii_custom_instruction_master_translator_multi_ci_master_writerc),   //                .writerc
		.multi_ci_master_a         (nios_ii_custom_instruction_master_translator_multi_ci_master_a),         //                .a
		.multi_ci_master_b         (nios_ii_custom_instruction_master_translator_multi_ci_master_b),         //                .b
		.multi_ci_master_c         (nios_ii_custom_instruction_master_translator_multi_ci_master_c),         //                .c
		.ci_slave_dataa            (32'b00000000000000000000000000000000),                                   //     (terminated)
		.ci_slave_datab            (32'b00000000000000000000000000000000),                                   //     (terminated)
		.ci_slave_n                (8'b00000000),                                                            //     (terminated)
		.ci_slave_readra           (1'b0),                                                                   //     (terminated)
		.ci_slave_readrb           (1'b0),                                                                   //     (terminated)
		.ci_slave_writerc          (1'b0),                                                                   //     (terminated)
		.ci_slave_a                (5'b00000),                                                               //     (terminated)
		.ci_slave_b                (5'b00000),                                                               //     (terminated)
		.ci_slave_c                (5'b00000),                                                               //     (terminated)
		.ci_slave_ipending         (32'b00000000000000000000000000000000),                                   //     (terminated)
		.ci_slave_estatus          (1'b0),                                                                   //     (terminated)
		.comb_ci_master_dataa      (),                                                                       //     (terminated)
		.comb_ci_master_datab      (),                                                                       //     (terminated)
		.comb_ci_master_n          (),                                                                       //     (terminated)
		.comb_ci_master_readra     (),                                                                       //     (terminated)
		.comb_ci_master_readrb     (),                                                                       //     (terminated)
		.comb_ci_master_writerc    (),                                                                       //     (terminated)
		.comb_ci_master_a          (),                                                                       //     (terminated)
		.comb_ci_master_b          (),                                                                       //     (terminated)
		.comb_ci_master_c          (),                                                                       //     (terminated)
		.comb_ci_master_ipending   (),                                                                       //     (terminated)
		.comb_ci_master_estatus    ()                                                                        //     (terminated)
	);

	signal_analyzer_NIOS_II_custom_instruction_master_multi_xconnect nios_ii_custom_instruction_master_multi_xconnect (
		.ci_slave_dataa       (nios_ii_custom_instruction_master_translator_multi_ci_master_dataa),     //   ci_slave.dataa
		.ci_slave_datab       (nios_ii_custom_instruction_master_translator_multi_ci_master_datab),     //           .datab
		.ci_slave_result      (nios_ii_custom_instruction_master_translator_multi_ci_master_result),    //           .result
		.ci_slave_n           (nios_ii_custom_instruction_master_translator_multi_ci_master_n),         //           .n
		.ci_slave_readra      (nios_ii_custom_instruction_master_translator_multi_ci_master_readra),    //           .readra
		.ci_slave_readrb      (nios_ii_custom_instruction_master_translator_multi_ci_master_readrb),    //           .readrb
		.ci_slave_writerc     (nios_ii_custom_instruction_master_translator_multi_ci_master_writerc),   //           .writerc
		.ci_slave_a           (nios_ii_custom_instruction_master_translator_multi_ci_master_a),         //           .a
		.ci_slave_b           (nios_ii_custom_instruction_master_translator_multi_ci_master_b),         //           .b
		.ci_slave_c           (nios_ii_custom_instruction_master_translator_multi_ci_master_c),         //           .c
		.ci_slave_ipending    (),                                                                       //           .ipending
		.ci_slave_estatus     (),                                                                       //           .estatus
		.ci_slave_clk         (nios_ii_custom_instruction_master_translator_multi_ci_master_clk),       //           .clk
		.ci_slave_reset       (nios_ii_custom_instruction_master_translator_multi_ci_master_reset),     //           .reset
		.ci_slave_clken       (nios_ii_custom_instruction_master_translator_multi_ci_master_clk_en),    //           .clk_en
		.ci_slave_reset_req   (nios_ii_custom_instruction_master_translator_multi_ci_master_reset_req), //           .reset_req
		.ci_slave_start       (nios_ii_custom_instruction_master_translator_multi_ci_master_start),     //           .start
		.ci_slave_done        (nios_ii_custom_instruction_master_translator_multi_ci_master_done),      //           .done
		.ci_master0_dataa     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_dataa),      // ci_master0.dataa
		.ci_master0_datab     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_datab),      //           .datab
		.ci_master0_result    (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_result),     //           .result
		.ci_master0_n         (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_n),          //           .n
		.ci_master0_readra    (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_readra),     //           .readra
		.ci_master0_readrb    (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_readrb),     //           .readrb
		.ci_master0_writerc   (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_writerc),    //           .writerc
		.ci_master0_a         (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_a),          //           .a
		.ci_master0_b         (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_b),          //           .b
		.ci_master0_c         (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_c),          //           .c
		.ci_master0_ipending  (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_ipending),   //           .ipending
		.ci_master0_estatus   (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_estatus),    //           .estatus
		.ci_master0_clk       (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_clk),        //           .clk
		.ci_master0_reset     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_reset),      //           .reset
		.ci_master0_clken     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_clk_en),     //           .clk_en
		.ci_master0_reset_req (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_reset_req),  //           .reset_req
		.ci_master0_start     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_start),      //           .start
		.ci_master0_done      (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_done)        //           .done
	);

	altera_customins_slave_translator #(
		.N_WIDTH          (2),
		.USE_DONE         (1),
		.NUM_FIXED_CYCLES (1)
	) nios_ii_custom_instruction_master_multi_slave_translator0 (
		.ci_slave_dataa      (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_dataa),          //  ci_slave.dataa
		.ci_slave_datab      (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_datab),          //          .datab
		.ci_slave_result     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_result),         //          .result
		.ci_slave_n          (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_n),              //          .n
		.ci_slave_readra     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_readra),         //          .readra
		.ci_slave_readrb     (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_readrb),         //          .readrb
		.ci_slave_writerc    (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_writerc),        //          .writerc
		.ci_slave_a          (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_a),              //          .a
		.ci_slave_b          (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_b),              //          .b
		.ci_slave_c          (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_c),              //          .c
		.ci_slave_ipending   (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_ipending),       //          .ipending
		.ci_slave_estatus    (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_estatus),        //          .estatus
		.ci_slave_clk        (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_clk),            //          .clk
		.ci_slave_clken      (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_clk_en),         //          .clk_en
		.ci_slave_reset_req  (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_reset_req),      //          .reset_req
		.ci_slave_reset      (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_reset),          //          .reset
		.ci_slave_start      (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_start),          //          .start
		.ci_slave_done       (nios_ii_custom_instruction_master_multi_xconnect_ci_master0_done),           //          .done
		.ci_master_dataa     (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_dataa),  // ci_master.dataa
		.ci_master_datab     (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_datab),  //          .datab
		.ci_master_result    (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_result), //          .result
		.ci_master_n         (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_n),      //          .n
		.ci_master_clk       (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_clk),    //          .clk
		.ci_master_clken     (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_clk_en), //          .clk_en
		.ci_master_reset     (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_reset),  //          .reset
		.ci_master_start     (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_start),  //          .start
		.ci_master_done      (nios_ii_custom_instruction_master_multi_slave_translator0_ci_master_done),   //          .done
		.ci_master_readra    (),                                                                           // (terminated)
		.ci_master_readrb    (),                                                                           // (terminated)
		.ci_master_writerc   (),                                                                           // (terminated)
		.ci_master_a         (),                                                                           // (terminated)
		.ci_master_b         (),                                                                           // (terminated)
		.ci_master_c         (),                                                                           // (terminated)
		.ci_master_ipending  (),                                                                           // (terminated)
		.ci_master_estatus   (),                                                                           // (terminated)
		.ci_master_reset_req ()                                                                            // (terminated)
	);

	signal_analyzer_mm_interconnect_0 mm_interconnect_0 (
		.SDRAM_PLL_c0_clk                           (sdram_pll_c0_clk),                                      //                         SDRAM_PLL_c0.clk
		.DMA_IO_reset_n_reset_bridge_in_reset_reset (rst_controller_reset_out_reset),                        // DMA_IO_reset_n_reset_bridge_in_reset.reset
		.NIOS_II_reset_reset_bridge_in_reset_reset  (rst_controller_001_reset_out_reset),                    //  NIOS_II_reset_reset_bridge_in_reset.reset
		.DMA_IO_mm_read_address                     (dma_io_mm_read_address),                                //                       DMA_IO_mm_read.address
		.DMA_IO_mm_read_waitrequest                 (dma_io_mm_read_waitrequest),                            //                                     .waitrequest
		.DMA_IO_mm_read_byteenable                  (dma_io_mm_read_byteenable),                             //                                     .byteenable
		.DMA_IO_mm_read_read                        (dma_io_mm_read_read),                                   //                                     .read
		.DMA_IO_mm_read_readdata                    (dma_io_mm_read_readdata),                               //                                     .readdata
		.DMA_IO_mm_read_readdatavalid               (dma_io_mm_read_readdatavalid),                          //                                     .readdatavalid
		.DMA_IO_mm_write_address                    (dma_io_mm_write_address),                               //                      DMA_IO_mm_write.address
		.DMA_IO_mm_write_waitrequest                (dma_io_mm_write_waitrequest),                           //                                     .waitrequest
		.DMA_IO_mm_write_byteenable                 (dma_io_mm_write_byteenable),                            //                                     .byteenable
		.DMA_IO_mm_write_write                      (dma_io_mm_write_write),                                 //                                     .write
		.DMA_IO_mm_write_writedata                  (dma_io_mm_write_writedata),                             //                                     .writedata
		.GPIO_mm_write_address                      (gpio_mm_write_address),                                 //                        GPIO_mm_write.address
		.GPIO_mm_write_waitrequest                  (gpio_mm_write_waitrequest),                             //                                     .waitrequest
		.GPIO_mm_write_byteenable                   (gpio_mm_write_byteenable),                              //                                     .byteenable
		.GPIO_mm_write_write                        (gpio_mm_write_write),                                   //                                     .write
		.GPIO_mm_write_writedata                    (gpio_mm_write_writedata),                               //                                     .writedata
		.NIOS_II_data_master_address                (nios_ii_data_master_address),                           //                  NIOS_II_data_master.address
		.NIOS_II_data_master_waitrequest            (nios_ii_data_master_waitrequest),                       //                                     .waitrequest
		.NIOS_II_data_master_byteenable             (nios_ii_data_master_byteenable),                        //                                     .byteenable
		.NIOS_II_data_master_read                   (nios_ii_data_master_read),                              //                                     .read
		.NIOS_II_data_master_readdata               (nios_ii_data_master_readdata),                          //                                     .readdata
		.NIOS_II_data_master_readdatavalid          (nios_ii_data_master_readdatavalid),                     //                                     .readdatavalid
		.NIOS_II_data_master_write                  (nios_ii_data_master_write),                             //                                     .write
		.NIOS_II_data_master_writedata              (nios_ii_data_master_writedata),                         //                                     .writedata
		.NIOS_II_data_master_debugaccess            (nios_ii_data_master_debugaccess),                       //                                     .debugaccess
		.NIOS_II_instruction_master_address         (nios_ii_instruction_master_address),                    //           NIOS_II_instruction_master.address
		.NIOS_II_instruction_master_waitrequest     (nios_ii_instruction_master_waitrequest),                //                                     .waitrequest
		.NIOS_II_instruction_master_read            (nios_ii_instruction_master_read),                       //                                     .read
		.NIOS_II_instruction_master_readdata        (nios_ii_instruction_master_readdata),                   //                                     .readdata
		.NIOS_II_instruction_master_readdatavalid   (nios_ii_instruction_master_readdatavalid),              //                                     .readdatavalid
		.DEBUG_avalon_jtag_slave_address            (mm_interconnect_0_debug_avalon_jtag_slave_address),     //              DEBUG_avalon_jtag_slave.address
		.DEBUG_avalon_jtag_slave_write              (mm_interconnect_0_debug_avalon_jtag_slave_write),       //                                     .write
		.DEBUG_avalon_jtag_slave_read               (mm_interconnect_0_debug_avalon_jtag_slave_read),        //                                     .read
		.DEBUG_avalon_jtag_slave_readdata           (mm_interconnect_0_debug_avalon_jtag_slave_readdata),    //                                     .readdata
		.DEBUG_avalon_jtag_slave_writedata          (mm_interconnect_0_debug_avalon_jtag_slave_writedata),   //                                     .writedata
		.DEBUG_avalon_jtag_slave_waitrequest        (mm_interconnect_0_debug_avalon_jtag_slave_waitrequest), //                                     .waitrequest
		.DEBUG_avalon_jtag_slave_chipselect         (mm_interconnect_0_debug_avalon_jtag_slave_chipselect),  //                                     .chipselect
		.DMA_IO_csr_address                         (mm_interconnect_0_dma_io_csr_address),                  //                           DMA_IO_csr.address
		.DMA_IO_csr_write                           (mm_interconnect_0_dma_io_csr_write),                    //                                     .write
		.DMA_IO_csr_read                            (mm_interconnect_0_dma_io_csr_read),                     //                                     .read
		.DMA_IO_csr_readdata                        (mm_interconnect_0_dma_io_csr_readdata),                 //                                     .readdata
		.DMA_IO_csr_writedata                       (mm_interconnect_0_dma_io_csr_writedata),                //                                     .writedata
		.DMA_IO_csr_byteenable                      (mm_interconnect_0_dma_io_csr_byteenable),               //                                     .byteenable
		.DMA_IO_descriptor_slave_write              (mm_interconnect_0_dma_io_descriptor_slave_write),       //              DMA_IO_descriptor_slave.write
		.DMA_IO_descriptor_slave_writedata          (mm_interconnect_0_dma_io_descriptor_slave_writedata),   //                                     .writedata
		.DMA_IO_descriptor_slave_byteenable         (mm_interconnect_0_dma_io_descriptor_slave_byteenable),  //                                     .byteenable
		.DMA_IO_descriptor_slave_waitrequest        (mm_interconnect_0_dma_io_descriptor_slave_waitrequest), //                                     .waitrequest
		.FLASH_MEM_csr_address                      (mm_interconnect_0_flash_mem_csr_address),               //                        FLASH_MEM_csr.address
		.FLASH_MEM_csr_write                        (mm_interconnect_0_flash_mem_csr_write),                 //                                     .write
		.FLASH_MEM_csr_read                         (mm_interconnect_0_flash_mem_csr_read),                  //                                     .read
		.FLASH_MEM_csr_readdata                     (mm_interconnect_0_flash_mem_csr_readdata),              //                                     .readdata
		.FLASH_MEM_csr_writedata                    (mm_interconnect_0_flash_mem_csr_writedata),             //                                     .writedata
		.FLASH_MEM_data_address                     (mm_interconnect_0_flash_mem_data_address),              //                       FLASH_MEM_data.address
		.FLASH_MEM_data_write                       (mm_interconnect_0_flash_mem_data_write),                //                                     .write
		.FLASH_MEM_data_read                        (mm_interconnect_0_flash_mem_data_read),                 //                                     .read
		.FLASH_MEM_data_readdata                    (mm_interconnect_0_flash_mem_data_readdata),             //                                     .readdata
		.FLASH_MEM_data_writedata                   (mm_interconnect_0_flash_mem_data_writedata),            //                                     .writedata
		.FLASH_MEM_data_burstcount                  (mm_interconnect_0_flash_mem_data_burstcount),           //                                     .burstcount
		.FLASH_MEM_data_readdatavalid               (mm_interconnect_0_flash_mem_data_readdatavalid),        //                                     .readdatavalid
		.FLASH_MEM_data_waitrequest                 (mm_interconnect_0_flash_mem_data_waitrequest),          //                                     .waitrequest
		.GPIO_s0_address                            (mm_interconnect_0_gpio_s0_address),                     //                              GPIO_s0.address
		.GPIO_s0_write                              (mm_interconnect_0_gpio_s0_write),                       //                                     .write
		.GPIO_s0_read                               (mm_interconnect_0_gpio_s0_read),                        //                                     .read
		.GPIO_s0_readdata                           (mm_interconnect_0_gpio_s0_readdata),                    //                                     .readdata
		.GPIO_s0_writedata                          (mm_interconnect_0_gpio_s0_writedata),                   //                                     .writedata
		.GPIO_s0_burstcount                         (mm_interconnect_0_gpio_s0_burstcount),                  //                                     .burstcount
		.GPIO_s0_byteenable                         (mm_interconnect_0_gpio_s0_byteenable),                  //                                     .byteenable
		.GPIO_s0_readdatavalid                      (mm_interconnect_0_gpio_s0_readdatavalid),               //                                     .readdatavalid
		.GPIO_s0_waitrequest                        (mm_interconnect_0_gpio_s0_waitrequest),                 //                                     .waitrequest
		.GPIO_s0_debugaccess                        (mm_interconnect_0_gpio_s0_debugaccess),                 //                                     .debugaccess
		.IO_Modules_s0_address                      (mm_interconnect_0_io_modules_s0_address),               //                        IO_Modules_s0.address
		.IO_Modules_s0_write                        (mm_interconnect_0_io_modules_s0_write),                 //                                     .write
		.IO_Modules_s0_read                         (mm_interconnect_0_io_modules_s0_read),                  //                                     .read
		.IO_Modules_s0_readdata                     (mm_interconnect_0_io_modules_s0_readdata),              //                                     .readdata
		.IO_Modules_s0_writedata                    (mm_interconnect_0_io_modules_s0_writedata),             //                                     .writedata
		.IO_Modules_s0_burstcount                   (mm_interconnect_0_io_modules_s0_burstcount),            //                                     .burstcount
		.IO_Modules_s0_byteenable                   (mm_interconnect_0_io_modules_s0_byteenable),            //                                     .byteenable
		.IO_Modules_s0_readdatavalid                (mm_interconnect_0_io_modules_s0_readdatavalid),         //                                     .readdatavalid
		.IO_Modules_s0_waitrequest                  (mm_interconnect_0_io_modules_s0_waitrequest),           //                                     .waitrequest
		.IO_Modules_s0_debugaccess                  (mm_interconnect_0_io_modules_s0_debugaccess),           //                                     .debugaccess
		.NIOS_II_debug_mem_slave_address            (mm_interconnect_0_nios_ii_debug_mem_slave_address),     //              NIOS_II_debug_mem_slave.address
		.NIOS_II_debug_mem_slave_write              (mm_interconnect_0_nios_ii_debug_mem_slave_write),       //                                     .write
		.NIOS_II_debug_mem_slave_read               (mm_interconnect_0_nios_ii_debug_mem_slave_read),        //                                     .read
		.NIOS_II_debug_mem_slave_readdata           (mm_interconnect_0_nios_ii_debug_mem_slave_readdata),    //                                     .readdata
		.NIOS_II_debug_mem_slave_writedata          (mm_interconnect_0_nios_ii_debug_mem_slave_writedata),   //                                     .writedata
		.NIOS_II_debug_mem_slave_byteenable         (mm_interconnect_0_nios_ii_debug_mem_slave_byteenable),  //                                     .byteenable
		.NIOS_II_debug_mem_slave_waitrequest        (mm_interconnect_0_nios_ii_debug_mem_slave_waitrequest), //                                     .waitrequest
		.NIOS_II_debug_mem_slave_debugaccess        (mm_interconnect_0_nios_ii_debug_mem_slave_debugaccess), //                                     .debugaccess
		.SDRAM_s1_address                           (mm_interconnect_0_sdram_s1_address),                    //                             SDRAM_s1.address
		.SDRAM_s1_write                             (mm_interconnect_0_sdram_s1_write),                      //                                     .write
		.SDRAM_s1_read                              (mm_interconnect_0_sdram_s1_read),                       //                                     .read
		.SDRAM_s1_readdata                          (mm_interconnect_0_sdram_s1_readdata),                   //                                     .readdata
		.SDRAM_s1_writedata                         (mm_interconnect_0_sdram_s1_writedata),                  //                                     .writedata
		.SDRAM_s1_byteenable                        (mm_interconnect_0_sdram_s1_byteenable),                 //                                     .byteenable
		.SDRAM_s1_readdatavalid                     (mm_interconnect_0_sdram_s1_readdatavalid),              //                                     .readdatavalid
		.SDRAM_s1_waitrequest                       (mm_interconnect_0_sdram_s1_waitrequest),                //                                     .waitrequest
		.SDRAM_s1_chipselect                        (mm_interconnect_0_sdram_s1_chipselect),                 //                                     .chipselect
		.SYS_ID_control_slave_address               (mm_interconnect_0_sys_id_control_slave_address),        //                 SYS_ID_control_slave.address
		.SYS_ID_control_slave_readdata              (mm_interconnect_0_sys_id_control_slave_readdata)        //                                     .readdata
	);

	signal_analyzer_irq_mapper irq_mapper (
		.clk           (sdram_pll_c0_clk),                   //       clk.clk
		.reset         (rst_controller_001_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),           // receiver0.irq
		.receiver1_irq (irq_mapper_receiver1_irq),           // receiver1.irq
		.receiver2_irq (irq_mapper_receiver2_irq),           // receiver2.irq
		.sender_irq    (nios_ii_irq_irq)                     //    sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (nios_ii_debug_reset_request_reset), // reset_in0.reset
		.clk            (sdram_pll_c0_clk),                  //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),    // reset_out.reset
		.reset_req      (),                                  // (terminated)
		.reset_req_in0  (1'b0),                              // (terminated)
		.reset_in1      (1'b0),                              // (terminated)
		.reset_req_in1  (1'b0),                              // (terminated)
		.reset_in2      (1'b0),                              // (terminated)
		.reset_req_in2  (1'b0),                              // (terminated)
		.reset_in3      (1'b0),                              // (terminated)
		.reset_req_in3  (1'b0),                              // (terminated)
		.reset_in4      (1'b0),                              // (terminated)
		.reset_req_in4  (1'b0),                              // (terminated)
		.reset_in5      (1'b0),                              // (terminated)
		.reset_req_in5  (1'b0),                              // (terminated)
		.reset_in6      (1'b0),                              // (terminated)
		.reset_req_in6  (1'b0),                              // (terminated)
		.reset_in7      (1'b0),                              // (terminated)
		.reset_req_in7  (1'b0),                              // (terminated)
		.reset_in8      (1'b0),                              // (terminated)
		.reset_req_in8  (1'b0),                              // (terminated)
		.reset_in9      (1'b0),                              // (terminated)
		.reset_req_in9  (1'b0),                              // (terminated)
		.reset_in10     (1'b0),                              // (terminated)
		.reset_req_in10 (1'b0),                              // (terminated)
		.reset_in11     (1'b0),                              // (terminated)
		.reset_req_in11 (1'b0),                              // (terminated)
		.reset_in12     (1'b0),                              // (terminated)
		.reset_req_in12 (1'b0),                              // (terminated)
		.reset_in13     (1'b0),                              // (terminated)
		.reset_req_in13 (1'b0),                              // (terminated)
		.reset_in14     (1'b0),                              // (terminated)
		.reset_req_in14 (1'b0),                              // (terminated)
		.reset_in15     (1'b0),                              // (terminated)
		.reset_req_in15 (1'b0)                               // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (nios_ii_debug_reset_request_reset),      // reset_in0.reset
		.reset_in1      (nios_ii_debug_reset_request_reset),      // reset_in1.reset
		.clk            (sdram_pll_c0_clk),                       //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_001_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                                   // (terminated)
		.reset_req_in1  (1'b0),                                   // (terminated)
		.reset_in2      (1'b0),                                   // (terminated)
		.reset_req_in2  (1'b0),                                   // (terminated)
		.reset_in3      (1'b0),                                   // (terminated)
		.reset_req_in3  (1'b0),                                   // (terminated)
		.reset_in4      (1'b0),                                   // (terminated)
		.reset_req_in4  (1'b0),                                   // (terminated)
		.reset_in5      (1'b0),                                   // (terminated)
		.reset_req_in5  (1'b0),                                   // (terminated)
		.reset_in6      (1'b0),                                   // (terminated)
		.reset_req_in6  (1'b0),                                   // (terminated)
		.reset_in7      (1'b0),                                   // (terminated)
		.reset_req_in7  (1'b0),                                   // (terminated)
		.reset_in8      (1'b0),                                   // (terminated)
		.reset_req_in8  (1'b0),                                   // (terminated)
		.reset_in9      (1'b0),                                   // (terminated)
		.reset_req_in9  (1'b0),                                   // (terminated)
		.reset_in10     (1'b0),                                   // (terminated)
		.reset_req_in10 (1'b0),                                   // (terminated)
		.reset_in11     (1'b0),                                   // (terminated)
		.reset_req_in11 (1'b0),                                   // (terminated)
		.reset_in12     (1'b0),                                   // (terminated)
		.reset_req_in12 (1'b0),                                   // (terminated)
		.reset_in13     (1'b0),                                   // (terminated)
		.reset_req_in13 (1'b0),                                   // (terminated)
		.reset_in14     (1'b0),                                   // (terminated)
		.reset_req_in14 (1'b0),                                   // (terminated)
		.reset_in15     (1'b0),                                   // (terminated)
		.reset_req_in15 (1'b0)                                    // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (1),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_002 (
		.reset_in0      (nios_ii_debug_reset_request_reset),  // reset_in0.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_002_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_in1      (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
