# TCL File Generated by Component Editor 18.1
# Wed Mar 04 19:09:33 IST 2026
# DO NOT MODIFY


# 
# avalon_counter_interface "Avalon Counter Interface (NIOS)" v1.0
#  2026.03.04.19:09:33
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module avalon_counter_interface
# 
set_module_property DESCRIPTION ""
set_module_property NAME avalon_counter_interface
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME "Avalon Counter Interface (NIOS)"
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL avalon_counter_logic
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file avalon_counter_logic.v VERILOG PATH ../ip_cores/avalon_counter_logic.v TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter INITIAL_MAX_COUNT STD_LOGIC_VECTOR 100
set_parameter_property INITIAL_MAX_COUNT DEFAULT_VALUE 100
set_parameter_property INITIAL_MAX_COUNT DISPLAY_NAME INITIAL_MAX_COUNT
set_parameter_property INITIAL_MAX_COUNT TYPE STD_LOGIC_VECTOR
set_parameter_property INITIAL_MAX_COUNT UNITS None
set_parameter_property INITIAL_MAX_COUNT ALLOWED_RANGES 0:17179869183
set_parameter_property INITIAL_MAX_COUNT HDL_PARAMETER true
add_parameter INITIAL_SPEED STD_LOGIC_VECTOR 5000000
set_parameter_property INITIAL_SPEED DEFAULT_VALUE 5000000
set_parameter_property INITIAL_SPEED DISPLAY_NAME INITIAL_SPEED
set_parameter_property INITIAL_SPEED TYPE STD_LOGIC_VECTOR
set_parameter_property INITIAL_SPEED UNITS None
set_parameter_property INITIAL_SPEED ALLOWED_RANGES 0:17179869183
set_parameter_property INITIAL_SPEED HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point s0
# 
add_interface s0 avalon end
set_interface_property s0 addressUnits WORDS
set_interface_property s0 associatedClock clock
set_interface_property s0 associatedReset reset
set_interface_property s0 bitsPerSymbol 8
set_interface_property s0 burstOnBurstBoundariesOnly false
set_interface_property s0 burstcountUnits WORDS
set_interface_property s0 explicitAddressSpan 0
set_interface_property s0 holdTime 0
set_interface_property s0 linewrapBursts false
set_interface_property s0 maximumPendingReadTransactions 0
set_interface_property s0 maximumPendingWriteTransactions 0
set_interface_property s0 readLatency 1
set_interface_property s0 readWaitTime 1
set_interface_property s0 setupTime 0
set_interface_property s0 timingUnits Cycles
set_interface_property s0 writeWaitTime 0
set_interface_property s0 ENABLED true
set_interface_property s0 EXPORT_OF ""
set_interface_property s0 PORT_NAME_MAP ""
set_interface_property s0 CMSIS_SVD_VARIABLES ""
set_interface_property s0 SVD_ADDRESS_GROUP ""

add_interface_port s0 avs_s0_address address Input 2
add_interface_port s0 avs_s0_write write Input 1
add_interface_port s0 avs_s0_writedata writedata Input 32
add_interface_port s0 avs_s0_read read Input 1
add_interface_port s0 avs_s0_readdata readdata Output 32
set_interface_assignment s0 embeddedsw.configuration.isFlash 0
set_interface_assignment s0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment s0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment s0 embeddedsw.configuration.isPrintableDevice 0

